function session = createSessionSpec(options)
%CREATESESSIONSPEC Contrato común de sesión para barras.

arguments
    options.name (1,1) string = "REGULAR"
    options.timezone (1,1) string = "UTC"
    options.mode (1,1) string = "REGULAR"
    options.startTime (1,1) duration = duration(0,0,0)
    options.endTime (1,1) duration = duration(24,0,0)
    options.expectedBarMinutes (1,1) double {mustBePositive} = 1
    options.expectedBarsPerSession (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.weekdays double = 1:7
end

mode = upper(options.mode);

if ~ismember(mode,["REGULAR","24X7"])
    error("QuantLab:SessionMode", ...
        "Modo de sesión no soportado: %s",mode);
end

session = struct( ...
    "name",options.name, ...
    "timezone",options.timezone, ...
    "mode",mode, ...
    "startTime",options.startTime, ...
    "endTime",options.endTime, ...
    "expectedBarMinutes",options.expectedBarMinutes, ...
    "expectedBarsPerSession",options.expectedBarsPerSession, ...
    "weekdays",reshape(options.weekdays,1,[]));
end
