function plan = buildWalkForwardWindows( ...
    data,trainingSessions,validationSessions,stepSessions, ...
    holdoutPct,windowMode)
%BUILDWALKFORWARDWINDOWS Construye ventanas temporales sin mirar resultados.
%
% windowMode:
%   "ANCHORED" - el inicio del entrenamiento permanece fijo.
%   "ROLLING"  - la ventana de entrenamiento conserva longitud fija.
%
% El holdout siempre ocupa las últimas sesiones y no participa en la
% selección de parámetros.

arguments
    data table
    trainingSessions (1,1) double ...
        {mustBeInteger,mustBePositive}
    validationSessions (1,1) double ...
        {mustBeInteger,mustBePositive}
    stepSessions (1,1) double ...
        {mustBeInteger,mustBePositive}
    holdoutPct (1,1) double ...
        {mustBeGreaterThanOrEqual(holdoutPct,0), ...
         mustBeLessThan(holdoutPct,50)} = 15
    windowMode (1,1) string = "ANCHORED"
end

windowMode = upper(windowMode);

if ~ismember(windowMode,["ANCHORED","ROLLING"])
    error("QuantLab:WalkForwardMode", ...
        "Modo no válido: %s",windowMode);
end

rowDates = extractOptimizationSessionDates(data);
sessionDates = unique(rowDates,"sorted");
totalSessions = numel(sessionDates);

if totalSessions<trainingSessions+validationSessions
    error("QuantLab:WalkForwardInsufficientData", ...
        ["Se necesitan al menos %d sesiones y solo hay %d. " + ...
         "Reduce Training o Validation."], ...
        trainingSessions+validationSessions,totalSessions);
end

holdoutSessions = floor(totalSessions*holdoutPct/100);

if holdoutPct>0 && holdoutSessions==0
    holdoutSessions = 1;
end

developmentSessions = totalSessions-holdoutSessions;

if developmentSessions<trainingSessions+validationSessions
    error("QuantLab:WalkForwardHoldoutTooLarge", ...
        ["Tras reservar el holdout quedan %d sesiones; " + ...
         "se necesitan %d."], ...
        developmentSessions,trainingSessions+validationSessions);
end

rows = cell(0,10);
windowIndex = 0;
trainStartIndex = 1;
trainEndIndex = trainingSessions;

while true
    validationStartIndex = trainEndIndex+1;
    validationEndIndex = ...
        validationStartIndex+validationSessions-1;

    if validationEndIndex>developmentSessions
        break;
    end

    windowIndex = windowIndex+1;

    rows(end+1,:) = { ... %#ok<AGROW>
        windowIndex, ...
        "WF" + string(sprintf("%02d",windowIndex)), ...
        windowMode, ...
        sessionDates(trainStartIndex), ...
        sessionDates(trainEndIndex), ...
        sessionDates(validationStartIndex), ...
        sessionDates(validationEndIndex), ...
        trainEndIndex-trainStartIndex+1, ...
        validationEndIndex-validationStartIndex+1, ...
        validationEndIndex};

    if windowMode=="ANCHORED"
        trainEndIndex = trainEndIndex+stepSessions;
    else
        trainStartIndex = trainStartIndex+stepSessions;
        trainEndIndex = trainStartIndex+trainingSessions-1;
    end

    if trainEndIndex>=developmentSessions
        break;
    end
end

if isempty(rows)
    error("QuantLab:WalkForwardNoWindows", ...
        "La configuración no genera ninguna ventana walk-forward.");
end

windows = cell2table(rows, ...
    'VariableNames',{ ...
    'window_index','window_id','mode', ...
    'train_start','train_end', ...
    'validation_start','validation_end', ...
    'train_sessions','validation_sessions', ...
    'development_end_index'});

holdout = struct( ...
    "reserved",holdoutSessions>0, ...
    "sessions",holdoutSessions, ...
    "start",NaT, ...
    "end",NaT, ...
    "status","NOT_RESERVED");

if holdoutSessions>0
    holdout.start = sessionDates(developmentSessions+1);
    holdout.end = sessionDates(end);
    holdout.status = "LOCKED";
end

plan = struct( ...
    "windows",windows, ...
    "holdout",holdout, ...
    "total_sessions",totalSessions, ...
    "development_sessions",developmentSessions, ...
    "training_sessions",trainingSessions, ...
    "validation_sessions",validationSessions, ...
    "step_sessions",stepSessions, ...
    "holdout_pct",holdoutPct, ...
    "mode",windowMode);
end
