function metrics = createEmptyOptimizationMetrics()
%CREATEEMPTYOPTIMIZATIONMETRICS Plantilla estable de salida.

metrics = struct( ...
    "status","ERROR", ...
    "error_message","", ...
    "executed_trades",0, ...
    "win_rate_pct",NaN, ...
    "net_r",NaN, ...
    "net_pnl_usd",NaN, ...
    "return_pct",NaN, ...
    "profit_factor",NaN, ...
    "expectancy_r",NaN, ...
    "max_drawdown_pct",NaN, ...
    "final_equity_usd",NaN, ...
    "top_10_contribution_pct",NaN, ...
    "target_exit_count",0, ...
    "stop_exit_count",0, ...
    "eod_exit_count",0, ...
    "other_exit_count",0, ...
    "behavior_signature","EMPTY", ...
    "is_count",0, ...
    "is_expectancy_r",NaN, ...
    "is_net_pnl_usd",NaN, ...
    "oos_count",0, ...
    "oos_expectancy_r",NaN, ...
    "oos_net_pnl_usd",NaN, ...
    "oos_profit_factor",NaN, ...
    "oos_max_drawdown_pct",NaN, ...
    "oos_target_exit_count",0, ...
    "oos_stop_exit_count",0, ...
    "oos_eod_exit_count",0, ...
    "oos_behavior_signature","EMPTY", ...
    "return_drawdown_ratio",NaN, ...
    "robustness_score",NaN, ...
    "stable_sign","N/A");
end
