function [results,cache,runState] = runParameterSweep( ...
    strategyName,profileName,trainingPct,grid, ...
    runnerFcn,cache,callbacks,cacheNamespace)
%RUNPARAMETERSWEEP Motor genérico full-grid con caché y cancelación.
%
% runnerFcn:
%   metrics = runnerFcn(parameterSet)
%
% callbacks.progress:
%   progress(completed,total,currentResult)
%
% callbacks.cancel:
%   logical = cancel()

arguments
    strategyName (1,1) string
    profileName (1,1) string
    trainingPct (1,1) double
    grid table
    runnerFcn (1,1) function_handle
    cache = []
    callbacks (1,1) struct = struct()
    cacheNamespace (1,1) string = "FULL"
end

if isempty(cache)
    cache = containers.Map( ...
        "KeyType","char", ...
        "ValueType","any");
end

if ~isa(cache,"containers.Map")
    error("QuantLab:OptimizationCacheType", ...
        "La caché debe ser containers.Map.");
end

hasProgress = isfield(callbacks,"progress") && ...
    isa(callbacks.progress,"function_handle");

hasCancel = isfield(callbacks,"cancel") && ...
    isa(callbacks.cancel,"function_handle");

progressStride = max(1,ceil(height(grid)/25));
progressIntervalSeconds = 0.20;

if isfield(callbacks,"progress_stride")
    progressStride = max(1,round(callbacks.progress_stride));
end

if isfield(callbacks,"progress_interval_seconds")
    progressIntervalSeconds = max( ...
        0,double(callbacks.progress_interval_seconds));
end

lastProgressClock = tic;

resultRows = repmat( ...
    createResultRowTemplate(),height(grid),1);

completed = 0;
cancelled = false;

for i = 1:height(grid)
    if hasCancel && callbacks.cancel()
        cancelled = true;
        break;
    end

    parameterSet = grid.parameter_set{i};
    cacheKey = buildOptimizationCacheKey( ...
        strategyName,profileName,trainingPct, ...
        parameterSet,cacheNamespace);

    startTime = tic;
    fromCache = false;

    if isKey(cache,char(cacheKey))
        metrics = cache(char(cacheKey));
        fromCache = true;
    else
        try
            metrics = runnerFcn(parameterSet);

            if ~isstruct(metrics)
                error("QuantLab:OptimizationRunnerOutput", ...
                    "El runner debe devolver una estructura.");
            end
        catch ME
            metrics = createEmptyOptimizationMetrics();
            metrics.status = "ERROR";
            metrics.error_message = string(ME.message);
        end

        cache(char(cacheKey)) = metrics;
    end

    elapsedSeconds = toc(startTime);

    resultRows(i) = mergeGridAndMetrics( ...
        grid(i,:),metrics,fromCache,elapsedSeconds);

    completed = i;

    shouldReport = ...
        i==1 || ...
        i==height(grid) || ...
        mod(i,progressStride)==0 || ...
        toc(lastProgressClock)>=progressIntervalSeconds;

    if hasProgress && shouldReport
        callbacks.progress( ...
            completed,height(grid),resultRows(i));
        lastProgressClock = tic;
    end
end

resultRows = resultRows(1:completed);

if isempty(resultRows)
    results = table();
else
    results = struct2table(resultRows);
    results = annotateParameterActivity(results);
end

runState = struct( ...
    "requested",height(grid), ...
    "completed",completed, ...
    "cancelled",cancelled, ...
    "cache_size",cache.Count);
end

function row = createResultRowTemplate()
metrics = createEmptyOptimizationMetrics();

row = struct( ...
    "combination_id",0, ...
    "parameter_set",{{table()}}, ...
    "parameter_1_name","", ...
    "parameter_1_label","", ...
    "parameter_1_value",NaN, ...
    "parameter_2_name","", ...
    "parameter_2_label","", ...
    "parameter_2_value",NaN, ...
    "status",metrics.status, ...
    "error_message",metrics.error_message, ...
    "executed_trades",metrics.executed_trades, ...
    "win_rate_pct",metrics.win_rate_pct, ...
    "net_r",metrics.net_r, ...
    "net_pnl_usd",metrics.net_pnl_usd, ...
    "return_pct",metrics.return_pct, ...
    "profit_factor",metrics.profit_factor, ...
    "expectancy_r",metrics.expectancy_r, ...
    "max_drawdown_pct",metrics.max_drawdown_pct, ...
    "final_equity_usd",metrics.final_equity_usd, ...
    "top_10_contribution_pct", ...
        metrics.top_10_contribution_pct, ...
    "target_exit_count",metrics.target_exit_count, ...
    "stop_exit_count",metrics.stop_exit_count, ...
    "eod_exit_count",metrics.eod_exit_count, ...
    "other_exit_count",metrics.other_exit_count, ...
    "behavior_signature",metrics.behavior_signature, ...
    "is_count",metrics.is_count, ...
    "is_expectancy_r",metrics.is_expectancy_r, ...
    "is_net_pnl_usd",metrics.is_net_pnl_usd, ...
    "oos_count",metrics.oos_count, ...
    "oos_expectancy_r",metrics.oos_expectancy_r, ...
    "oos_net_pnl_usd",metrics.oos_net_pnl_usd, ...
    "oos_profit_factor",metrics.oos_profit_factor, ...
    "oos_max_drawdown_pct", ...
        metrics.oos_max_drawdown_pct, ...
    "oos_target_exit_count",metrics.oos_target_exit_count, ...
    "oos_stop_exit_count",metrics.oos_stop_exit_count, ...
    "oos_eod_exit_count",metrics.oos_eod_exit_count, ...
    "oos_behavior_signature",metrics.oos_behavior_signature, ...
    "return_drawdown_ratio", ...
        metrics.return_drawdown_ratio, ...
    "robustness_score",metrics.robustness_score, ...
    "stable_sign",metrics.stable_sign, ...
    "from_cache",false, ...
    "elapsed_seconds",NaN);
end

function row = mergeGridAndMetrics( ...
    gridRow,metrics,fromCache,elapsedSeconds)

row = createResultRowTemplate();

row.combination_id = gridRow.combination_id;
row.parameter_set = gridRow.parameter_set;
row.parameter_1_name = gridRow.parameter_1_name;
row.parameter_1_label = gridRow.parameter_1_label;
row.parameter_1_value = gridRow.parameter_1_value;
row.parameter_2_name = gridRow.parameter_2_name;
row.parameter_2_label = gridRow.parameter_2_label;
row.parameter_2_value = gridRow.parameter_2_value;

metricFields = string(fieldnames(metrics));

for field = metricFields'
    if isfield(row,field)
        row.(field) = metrics.(field);
    end
end

row.from_cache = fromCache;
row.elapsed_seconds = elapsedSeconds;
end
