function [walkForwardResult,cache,runState] = ...
    runWalkForwardOptimization( ...
    strategyName,profileName,data,grid,plan,selectionMetric, ...
    innerTrainingPct,runnerFactory,cache,callbacks, ...
    evaluateHoldout)
%RUNWALKFORWARDOPTIMIZATION Multi-window IS/OOS optimization engine.
%
% runnerFactory(dataSlice,phaseName,windowId) must return:
%   runnerFcn(parameterSet) -> optimization metrics struct
%
% The final holdout is excluded from all optimization and aggregation.

arguments
    strategyName (1,1) string
    profileName (1,1) string
    data table
    grid table
    plan (1,1) struct
    selectionMetric (1,1) string
    innerTrainingPct (1,1) double
    runnerFactory (1,1) function_handle
    cache = []
    callbacks (1,1) struct = struct()
    evaluateHoldout (1,1) logical = false
end

if isempty(cache)
    cache = containers.Map( ...
        "KeyType","char","ValueType","any");
end

hasProgress = isfield(callbacks,"progress") && ...
    isa(callbacks.progress,"function_handle");
hasCancel = isfield(callbacks,"cancel") && ...
    isa(callbacks.cancel,"function_handle");

windows = plan.windows;
windowCount = height(windows);
combinationCount = height(grid);
requestedRuns = windowCount*combinationCount*2;

if evaluateHoldout && plan.holdout.reserved
    requestedRuns = requestedRuns+1;
end

trainingSweeps = cell(windowCount,1);
validationSweeps = cell(windowCount,1);
windowRows = repmat(createWindowTemplate(),windowCount,1);
selectedIds = nan(windowCount,1);

completedRuns = 0;
completedWindows = 0;
cancelled = false;

for windowIndex = 1:windowCount
    if shouldCancel()
        cancelled = true;
        break;
    end

    window = windows(windowIndex,:);
    trainData = sliceMarketDataBySession( ...
        data,window.train_start,window.train_end);
    validationData = sliceMarketDataBySession( ...
        data,window.validation_start,window.validation_end);

    trainRunner = runnerFactory( ...
        trainData,"TRAIN",window.window_id);

    phaseBase = completedRuns;
    trainCallbacks = struct( ...
        "progress",@(localCompleted,~,row) ...
            reportProgress(phaseBase+localCompleted, ...
            "TRAIN",windowIndex,row), ...
        "cancel",@shouldCancel);

    trainNamespace = buildWindowNamespace( ...
        window,"TRAIN");

    [trainResults,cache,trainState] = runParameterSweep( ...
        strategyName,profileName,innerTrainingPct, ...
        grid,trainRunner,cache,trainCallbacks,trainNamespace);

    completedRuns = phaseBase+trainState.completed;

    if trainState.cancelled || ...
            trainState.completed<combinationCount
        cancelled = true;
        break;
    end

    trainingSweeps{windowIndex} = trainResults;

    [bestTrain,bestIndex] = ...
        selectBestOptimizationResult( ...
            trainResults,selectionMetric);

    if isempty(bestTrain)
        windowRows(windowIndex) = ...
            buildFailedWindowRow(window, ...
                "NO_VALID_TRAINING_CONFIGURATION");
        completedWindows = windowIndex;
        continue;
    end

    validationRunner = runnerFactory( ...
        validationData,"VALIDATION",window.window_id);

    phaseBase = completedRuns;
    validationCallbacks = struct( ...
        "progress",@(localCompleted,~,row) ...
            reportProgress(phaseBase+localCompleted, ...
            "VALIDATION",windowIndex,row), ...
        "cancel",@shouldCancel);

    validationNamespace = buildWindowNamespace( ...
        window,"VALIDATION");

    [validationResults,cache,validationState] = ...
        runParameterSweep( ...
        strategyName,profileName,innerTrainingPct, ...
        grid,validationRunner,cache, ...
        validationCallbacks,validationNamespace);

    completedRuns = phaseBase+validationState.completed;

    if validationState.cancelled || ...
            validationState.completed<combinationCount
        cancelled = true;
        break;
    end

    validationSweeps{windowIndex} = validationResults;
    selectedId = bestTrain.combination_id(1);
    selectedIds(windowIndex) = selectedId;

    selectedValidation = validationResults( ...
        validationResults.combination_id==selectedId,:);

    if isempty(selectedValidation)
        windowRows(windowIndex) = ...
            buildFailedWindowRow(window, ...
                "SELECTED_CONFIGURATION_NOT_VALIDATED");
    else
        windowRows(windowIndex) = ...
            buildWindowRow( ...
                window,bestTrain,bestIndex, ...
                selectedValidation,selectionMetric);
    end

    completedWindows = windowIndex;
end

trainingSweeps = trainingSweeps(1:completedWindows);
validationSweeps = validationSweeps(1:completedWindows);
selectedIds = selectedIds(1:completedWindows);
windowRows = windowRows(1:completedWindows);

if isempty(windowRows)
    windowResults = table();
else
    windowResults = struct2table(windowRows);
end

aggregate = aggregateWalkForwardResults( ...
    grid,trainingSweeps,validationSweeps, ...
    selectedIds,selectionMetric);

consensus = selectConsensusConfiguration(aggregate);
holdout = buildHoldoutResult(plan.holdout,consensus);

if evaluateHoldout && plan.holdout.reserved && ...
        ~isempty(consensus) && ~shouldCancel()
    holdoutData = sliceMarketDataBySession( ...
        data,plan.holdout.start,plan.holdout.end);
    holdoutRunner = runnerFactory( ...
        holdoutData,"HOLDOUT","FINAL");
    holdoutGrid = grid( ...
        grid.combination_id==consensus.combination_id(1),:);

    phaseBase = completedRuns;
    holdoutCallbacks = struct( ...
        "progress",@(localCompleted,~,row) ...
            reportProgress(phaseBase+localCompleted, ...
            "HOLDOUT",windowCount+1,row), ...
        "cancel",@shouldCancel);

    [holdoutSweep,cache,holdoutState] = ...
        runParameterSweep( ...
        strategyName,profileName,innerTrainingPct, ...
        holdoutGrid,holdoutRunner,cache, ...
        holdoutCallbacks,"WF_FINAL_HOLDOUT");

    completedRuns = phaseBase+holdoutState.completed;

    if ~isempty(holdoutSweep) && ...
            holdoutSweep.status(1)=="OK"
        holdout = populateHoldoutResult( ...
            holdout,holdoutSweep(1,:));
    elseif holdoutState.cancelled
        cancelled = true;
        holdout.status = "CANCELLED";
    else
        holdout.status = "ERROR";
    end
end

runState = struct( ...
    "requested_runs",requestedRuns, ...
    "completed_runs",completedRuns, ...
    "requested_windows",windowCount, ...
    "completed_windows",completedWindows, ...
    "cancelled",cancelled || shouldCancel(), ...
    "cache_size",cache.Count, ...
    "holdout_evaluated",holdout.status=="EVALUATED");

walkForwardResult = struct( ...
    "plan",plan, ...
    "selection_metric",selectionMetric, ...
    "inner_training_pct",innerTrainingPct, ...
    "grid",grid, ...
    "window_results",windowResults, ...
    "aggregate_results",aggregate, ...
    "training_sweeps",{trainingSweeps}, ...
    "validation_sweeps",{validationSweeps}, ...
    "consensus",consensus, ...
    "holdout",holdout, ...
    "run_state",runState);

    function result = shouldCancel()
        result = false;
        if hasCancel
            result = logical(callbacks.cancel());
        end
    end

    function reportProgress(completed,phase,windowNumber,row)
        if ~hasProgress
            return;
        end

        callbacks.progress( ...
            completed,requestedRuns,phase, ...
            windowNumber,row);
    end
end

function namespace = buildWindowNamespace(window,phase)
namespace = "WF_" + phase + "_" + ...
    string(window.train_start,"yyyyMMdd") + "_" + ...
    string(window.train_end,"yyyyMMdd") + "_" + ...
    string(window.validation_start,"yyyyMMdd") + "_" + ...
    string(window.validation_end,"yyyyMMdd");
end

function template = createWindowTemplate()
template = struct( ...
    "window_index",0, ...
    "window_id","", ...
    "mode","", ...
    "train_start",NaT, ...
    "train_end",NaT, ...
    "validation_start",NaT, ...
    "validation_end",NaT, ...
    "train_sessions",0, ...
    "validation_sessions",0, ...
    "status","", ...
    "selected_combination_id",NaN, ...
    "parameter_1_label","", ...
    "parameter_1_value",NaN, ...
    "parameter_2_label","", ...
    "parameter_2_value",NaN, ...
    "train_selection_metric",NaN, ...
    "train_expectancy_r",NaN, ...
    "validation_expectancy_r",NaN, ...
    "validation_net_pnl_usd",NaN, ...
    "validation_return_pct",NaN, ...
    "validation_profit_factor",NaN, ...
    "validation_max_drawdown_pct",NaN, ...
    "expectancy_sign_stable","N/A");
end

function row = buildWindowRow( ...
    window,bestTrain,bestIndex,validation,selectionMetric)

[selectionField,~] = ...
    getOptimizationMetricDefinition(selectionMetric);

row = createWindowTemplate();
row.window_index = window.window_index;
row.window_id = window.window_id;
row.mode = window.mode;
row.train_start = window.train_start;
row.train_end = window.train_end;
row.validation_start = window.validation_start;
row.validation_end = window.validation_end;
row.train_sessions = window.train_sessions;
row.validation_sessions = window.validation_sessions;
row.status = "OK";
row.selected_combination_id = bestTrain.combination_id(1);
row.parameter_1_label = bestTrain.parameter_1_label(1);
row.parameter_1_value = bestTrain.parameter_1_value(1);
row.parameter_2_label = bestTrain.parameter_2_label(1);
row.parameter_2_value = bestTrain.parameter_2_value(1);
row.train_selection_metric = ...
    bestTrain.(selectionField)(1);
row.train_expectancy_r = bestTrain.expectancy_r(1);
row.validation_expectancy_r = validation.expectancy_r(1);
row.validation_net_pnl_usd = validation.net_pnl_usd(1);
row.validation_return_pct = validation.return_pct(1);
row.validation_profit_factor = validation.profit_factor(1);
row.validation_max_drawdown_pct = ...
    validation.max_drawdown_pct(1);

if isfinite(row.train_expectancy_r) && ...
        isfinite(row.validation_expectancy_r)
    if sign(row.train_expectancy_r)== ...
            sign(row.validation_expectancy_r)
        row.expectancy_sign_stable = "YES";
    else
        row.expectancy_sign_stable = "NO";
    end
end
end

function row = buildFailedWindowRow(window,status)
row = createWindowTemplate();
row.window_index = window.window_index;
row.window_id = window.window_id;
row.mode = window.mode;
row.train_start = window.train_start;
row.train_end = window.train_end;
row.validation_start = window.validation_start;
row.validation_end = window.validation_end;
row.train_sessions = window.train_sessions;
row.validation_sessions = window.validation_sessions;
row.status = status;
end

function consensus = selectConsensusConfiguration(aggregate)
consensus = table();

if isempty(aggregate)
    return;
end

valid = isfinite(aggregate.plateau_score);

if any(valid)
    candidates = aggregate(valid,:);
    candidates = sortrows( ...
        candidates,"plateau_score","descend");
    consensus = candidates(1,:);
    return;
end

valid = isfinite(aggregate.wf_robustness_score);

if any(valid)
    candidates = aggregate(valid,:);
    candidates = sortrows( ...
        candidates,"wf_robustness_score","descend");
    consensus = candidates(1,:);
end
end

function holdout = buildHoldoutResult(planHoldout,consensus)
holdout = struct( ...
    "reserved",planHoldout.reserved, ...
    "sessions",planHoldout.sessions, ...
    "start",planHoldout.start, ...
    "end",planHoldout.end, ...
    "status",planHoldout.status, ...
    "combination_id",NaN, ...
    "parameter_1_label","", ...
    "parameter_1_value",NaN, ...
    "parameter_2_label","", ...
    "parameter_2_value",NaN, ...
    "expectancy_r",NaN, ...
    "net_pnl_usd",NaN, ...
    "return_pct",NaN, ...
    "profit_factor",NaN, ...
    "max_drawdown_pct",NaN);

if ~isempty(consensus)
    holdout.combination_id = consensus.combination_id(1);
    holdout.parameter_1_label = consensus.parameter_1_label(1);
    holdout.parameter_1_value = consensus.parameter_1_value(1);
    holdout.parameter_2_label = consensus.parameter_2_label(1);
    holdout.parameter_2_value = consensus.parameter_2_value(1);
end
end

function holdout = populateHoldoutResult(holdout,result)
holdout.status = "EVALUATED";
holdout.expectancy_r = result.expectancy_r(1);
holdout.net_pnl_usd = result.net_pnl_usd(1);
holdout.return_pct = result.return_pct(1);
holdout.profit_factor = result.profit_factor(1);
holdout.max_drawdown_pct = result.max_drawdown_pct(1);
end
