function catalog = buildEMACrossFeatureCatalog()
%BUILDEMACROSSFEATURECATALOG Features conocidas en entrada.

rows = { ...
    "direction","Direction","categorical","","input", ...
        "Categories",true,"EMA_CROSS","Signal direction"; ...
    "fast_ema","Fast EMA","numeric","price","input", ...
        "Quintiles",true,"EMA_CROSS","Fast EMA at signal"; ...
    "slow_ema","Slow EMA","numeric","price","input", ...
        "Quintiles",true,"EMA_CROSS","Slow EMA at signal"; ...
    "ema_spread_points","EMA Spread","numeric","points","input", ...
        "Quintiles",true,"EMA_CROSS","Absolute EMA separation"; ...
    "atr_points","ATR","numeric","points","context", ...
        "Quintiles",true,"EMA_CROSS","ATR at signal"; ...
    "close_distance_to_fast","Close to Fast EMA","numeric","points", ...
        "context","Quintiles",true,"EMA_CROSS","Signal close minus fast EMA"; ...
    "day_of_week","Day of Week","categorical","","context", ...
        "Categories",true,"derived","Derived from session date"; ...
    "entry_hour","Entry Hour","numeric","hour","context", ...
        "Categories",true,"derived","Derived from entry timestamp"};

catalog = cell2table(rows, ...
    'VariableNames',{ ...
    'name','label','type','unit','role', ...
    'default_grouping','enabled','source','description'});
catalog = normalizeFeatureCatalog(catalog);
end
