function schema = buildEMACrossParameterSchema()
%BUILDEMACROSSPARAMETERSCHEMA Parámetros optimizables del plugin.

schema = table( ...
    ["emaCross.fastPeriod";"emaCross.slowPeriod"; ...
     "emaCross.atrPeriod";"emaCross.atrStopMultiple"; ...
     "emaCross.rewardRisk";"emaCross.maximumTradesPerSession"], ...
    ["Fast EMA Period";"Slow EMA Period";"ATR Period"; ...
     "ATR Stop Multiple";"Reward/Risk Target"; ...
     "Maximum Trades per Session"], ...
    ["integer";"integer";"integer";"numeric";"numeric";"integer"], ...
    [10;30;14;1.5;2;2], ...
    [2;5;2;0.25;0.5;1], ...
    [100;300;100;10;20;10], ...
    [1;5;1;0.25;0.5;1], ...
    [5;20;7;0.5;1;1], ...
    [30;80;30;3;6;4], ...
    ["bars";"bars";"bars";"ATR";"R";"trades"], ...
    true(6,1),true(6,1),true(6,1), ...
    ["Fast EMA length";"Slow EMA length";"ATR length"; ...
     "Initial stop in ATR multiples";"Profit target in risk multiples"; ...
     "Maximum entries accepted per session"], ...
    'VariableNames',{ ...
    'name','label','type','default_value','minimum','maximum', ...
    'step','sweep_start','sweep_stop','unit','enabled', ...
    'optimizable','rebuild_events','description'});

schema = normalizeParameterSchema(schema);
end
