clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

S = loadAuditWorkspace(matlabRoot,"ORB");

schema = getOptimizableParameterSchema( ...
    buildORBParameterSchema());

request = table( ...
    "orb.rewardRisk", ...
    "Reward/Risk Target", ...
    "numeric", ...
    3,4,1, ...
    'VariableNames',{ ...
    'name','label','type', ...
    'start_value','stop_value','step_value'});

grid = buildParameterSweepGrid(request,10);
selectedSchema = schema( ...
    schema.name=="orb.rewardRisk",:);

prepared = prepareStrategyOptimization( ...
    "ORB",S.data,S.cfg,selectedSchema);

assert(prepared.use_prepared_context);

runner = @(parameterSet) ...
    runStrategyOptimizationCombination( ...
        "ORB",S.data,S.cfg,parameterSet, ...
        "REALISTIC",70,prepared);

[results,~,state] = runParameterSweep( ...
    "ORB","REALISTIC",70,grid,runner);

assert(state.completed==2);
assert(height(results)==2);
assert(all(results.status=="OK"));
assert(all(results.executed_trades>0));
assert(all(isfinite(results.expectancy_r)));

fprintf("TEST ORB PARAMETER SWEEP SMOKE SUPERADO\n");
disp(results(:,{ ...
    'parameter_1_value','net_pnl_usd', ...
    'expectancy_r','max_drawdown_pct', ...
    'oos_expectancy_r'}));
