clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

metrics = createEmptyOptimizationMetrics();
metrics.status = "OK";
metrics.executed_trades = 83;
metrics.win_rate_pct = 19.2771;
metrics.net_r = 29.9029;
metrics.net_pnl_usd = -1213.9;
metrics.return_pct = -2.4278;
metrics.profit_factor = 0.7915;
metrics.expectancy_r = -0.2457;
metrics.max_drawdown_pct = 4.2031;
metrics.return_drawdown_ratio = -0.5776;
metrics.is_expectancy_r = 0.4991;
metrics.oos_expectancy_r = -0.00001234;
metrics.robustness_score = -1.0416;

results = table( ...
    1,{table()}, ...
    "p1","Parameter 1",9, ...
    "","",NaN, ...
    metrics.status,metrics.error_message, ...
    metrics.executed_trades,metrics.win_rate_pct, ...
    metrics.net_r,metrics.net_pnl_usd,metrics.return_pct, ...
    metrics.profit_factor,metrics.expectancy_r, ...
    metrics.max_drawdown_pct,metrics.final_equity_usd, ...
    metrics.top_10_contribution_pct, ...
    metrics.target_exit_count,metrics.stop_exit_count, ...
    metrics.eod_exit_count,metrics.other_exit_count, ...
    metrics.behavior_signature, ...
    metrics.is_count,metrics.is_expectancy_r, ...
    metrics.is_net_pnl_usd,metrics.oos_count, ...
    metrics.oos_expectancy_r,metrics.oos_net_pnl_usd, ...
    metrics.oos_profit_factor,metrics.oos_max_drawdown_pct, ...
    metrics.oos_target_exit_count,metrics.oos_stop_exit_count, ...
    metrics.oos_eod_exit_count,metrics.oos_behavior_signature, ...
    metrics.return_drawdown_ratio,metrics.robustness_score, ...
    metrics.stable_sign,false,0.012, ...
    1,1,"ACTIVE","ACTIVE","N/A", ...
    'VariableNames',{ ...
    'combination_id','parameter_set', ...
    'parameter_1_name','parameter_1_label','parameter_1_value', ...
    'parameter_2_name','parameter_2_label','parameter_2_value', ...
    'status','error_message','executed_trades','win_rate_pct', ...
    'net_r','net_pnl_usd','return_pct','profit_factor', ...
    'expectancy_r','max_drawdown_pct','final_equity_usd', ...
    'top_10_contribution_pct','target_exit_count', ...
    'stop_exit_count','eod_exit_count','other_exit_count', ...
    'behavior_signature','is_count','is_expectancy_r', ...
    'is_net_pnl_usd','oos_count','oos_expectancy_r', ...
    'oos_net_pnl_usd','oos_profit_factor', ...
    'oos_max_drawdown_pct','oos_target_exit_count', ...
    'oos_stop_exit_count','oos_eod_exit_count', ...
    'oos_behavior_signature','return_drawdown_ratio', ...
    'robustness_score','stable_sign','from_cache', ...
    'elapsed_seconds','behavior_group_id', ...
    'equivalent_configurations','activity_status', ...
    'parameter_1_activity','parameter_2_activity'});

displayTable = buildOptimizationDisplayTable( ...
    results,"Robustness");

assertNoScientificNotation(displayTable);

fprintf("TEST OPTIMIZATION PLAIN NUMBER TABLES SUPERADO\n");

function assertNoScientificNotation(inputTable)
cells = table2cell(inputTable);

for i = 1:numel(cells)
    value = cells{i};

    if isstring(value) || ischar(value)
        text = char(string(value));

        assert(isempty(regexp( ...
            text,'[eE][+-][0-9]+','once')), ...
            "Scientific notation found: %s",text);
    end
end
end
