clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

dashboardFile = fullfile( ...
    matlabRoot, ...
    "Dashboard", ...
    "launchQuantLabDashboard.m");

source = fileread(dashboardFile);

obsoleteFunctions = [ ...
    "function updateEquity("; ...
    "function updateVolume("; ...
    "function updateDrawdown("; ...
    "function updateExposure("; ...
    "function updateTurnover("; ...
    "function updateOrders("; ...
    "function updateTrades("];

for i = 1:numel(obsoleteFunctions)
    assert(~contains(source,obsoleteFunctions(i)), ...
        "Queda una función visual anidada obsoleta.");
end

requiredCalls = [ ...
    "updateEquityCharts("; ...
    "updateVolumeChart("; ...
    "updateDrawdownChart("; ...
    "updateExposureChart("; ...
    "updateTurnoverChart("; ...
    "updateOrdersTable("; ...
    "updateTradesTable("; ...
    "updateLogsPanel("];

for i = 1:numel(requiredCalls)
    assert(contains(source,requiredCalls(i)), ...
        "Falta una llamada al componente visual.");
end

requiredFiles = [ ...
    "updateEquityCharts.m"; ...
    "updateVolumeChart.m"; ...
    "updateDrawdownChart.m"; ...
    "updateExposureChart.m"; ...
    "updateTurnoverChart.m"; ...
    "updateOrdersTable.m"; ...
    "updateTradesTable.m"; ...
    "updateLogsPanel.m"];

for i = 1:numel(requiredFiles)
    assert(isfile(fullfile( ...
        matlabRoot, ...
        "Dashboard", ...
        "Components", ...
        requiredFiles(i))), ...
        "Falta un componente visual.");
end

fprintf("TEST DASHBOARD VISUAL COMPONENTS SUPERADO\n");
