clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

source = fileread(fullfile( ...
    matlabRoot,"Dashboard","launchQuantLabDashboard.m"));

assert(contains(source, ...
    "analyticsHost = uigridlayout(analyticsTab,[1 1])"), ...
    "Analytics no está alojado en un grid de tamaño completo.");

assert(contains(source, ...
    "analyticsTabs = uitabgroup(analyticsHost)"), ...
    "El tabgroup de Analytics no usa el host responsive.");

assert(contains(source, ...
    '"analyticsDirty",true'), ...
    "Falta el estado dirty de Calendar & Rolling.");

assert(contains(source, ...
    '"distributionDirty",true'), ...
    "Falta el estado dirty de Trade Distribution.");

assert(contains(source, ...
    "drawnow limitrate nocallbacks"), ...
    "El perfil principal no fuerza un repintado seguro.");

assert(contains(source, ...
    "if isequal(leftTabs.SelectedTab,analyticsTab)"), ...
    "Analytics no se carga de forma diferida.");

assert(contains(source, ...
    "safeRefreshCalendarRolling"), ...
    "Calendar & Rolling no está aislado.");

assert(contains(source, ...
    "safeRefreshDistribution"), ...
    "Trade Distribution no está aislado.");

refreshStart = strfind(source,"function refreshAll()");
refreshEnd = strfind(source,"function finishCoreRefresh()");
refreshText = extractBetween( ...
    string(source), ...
    refreshStart(1), ...
    refreshEnd(1)-1);

assert(~contains(refreshText, ...
    "updateAnalyticsDashboard("), ...
    "Analytics sigue bloqueando el camino crítico del perfil.");

assert(~contains(refreshText, ...
    "updateTradeDistributionDashboard("), ...
    "Trade Distribution sigue bloqueando el perfil.");

fprintf("TEST DASHBOARD LAZY ANALYTICS ARCHITECTURE SUPERADO\n");
