clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
source = fileread(fullfile( ...
    matlabRoot,"Dashboard","launchQuantLabDashboard.m"));

assert(contains(source, ...
    '"fullGridUiInitialized",false'));
assert(contains(source, ...
    '"walkForwardUiInitialized",false'));
assert(contains(source, ...
    "isInitializingDashboard = true"));
assert(contains(source, ...
    "isInitializingDashboard = false"));

startupSection = extractBetween( ...
    source, ...
    "isInitializingDashboard = true;", ...
    "app = struct(");

assert(~contains(startupSection, ...
    "refreshOptimizationResults();"), ...
    "Full Grid must not render during startup.");

assert(~contains(startupSection, ...
    "refreshWalkForwardResults();"), ...
    "Walk-Forward must not render during startup.");

assert(~contains(startupSection, ...
    "updateOptimizationEstimate();"), ...
    "Full Grid estimate must be lazy during startup.");

assert(~contains(startupSection, ...
    "updateWalkForwardEstimate();"), ...
    "Walk-Forward estimate must be lazy during startup.");

assert(contains(source, ...
    "if ~dashboardState.fullGridUiInitialized"));
assert(contains(source, ...
    "if ~dashboardState.walkForwardUiInitialized"));

fprintf("TEST DASHBOARD FAST STARTUP LAZY OPTIMIZATION SUPERADO\n");
