clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

componentRoot = fullfile( ...
    matlabRoot, ...
    "Dashboard", ...
    "Components");

checks = { ...
    "updateEquityCharts.m", ...
        "resetDashboardAxes(equityAxes);"; ...
    "updateEquityCharts.m", ...
        "resetDashboardAxes(returnAxes);"; ...
    "updateVolumeChart.m", ...
        "resetDashboardAxes(volumeAxes);"; ...
    "updateDrawdownChart.m", ...
        "resetDashboardAxes(drawdownAxes);"; ...
    "updateExposureChart.m", ...
        "resetDashboardAxes(exposureAxes);"; ...
    "updateTurnoverChart.m", ...
        "resetDashboardAxes(turnoverAxes);"};

for i = 1:size(checks,1)
    source = fileread(fullfile(componentRoot,checks{i,1}));

    assert(contains(source,checks{i,2}), ...
        "Falta limpieza completa en %s.", ...
        checks{i,1});
end

fig = uifigure("Visible","off");
cleanup = onCleanup(@() delete(fig));

ax = uiaxes(fig);

hold(ax,"on");

area(ax,1:3,[0 -1 -2], ...
    "HandleVisibility","off");

plot(ax,1:3,[0 -1 -2], ...
    "HandleVisibility","off");

yline(ax,0, ...
    "HandleVisibility","off");

assert(~isempty(allchild(ax)));

resetDashboardAxes(ax);

assert(isempty(allchild(ax)), ...
    "resetDashboardAxes no eliminó todos los objetos.");

fprintf("TEST ALL DASHBOARD CHARTS RESET SUPERADO\n");
