clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

S = loadAuditWorkspace(matlabRoot,"ORB");
request = table( ...
    "orb.rewardRisk","Reward/Risk Target", ...
    "numeric",3,4,1, ...
    'VariableNames',{ ...
    'name','label','type','start_value','stop_value','step_value'});

grid = buildParameterSweepGrid(request,10);
plan = buildWalkForwardWindows( ...
    S.data,100,30,30,10,"ANCHORED");

% Limitar el smoke test a las dos primeras ventanas.
plan.windows = plan.windows(1:min(2,height(plan.windows)),:);
selectedSchema = getOptimizableParameterSchema( ...
    buildORBParameterSchema());
selectedSchema = selectedSchema( ...
    selectedSchema.name=="orb.rewardRisk",:);

factory = @(slice,phase,windowId) ...
    createRunner(slice,phase,windowId, ...
        selectedSchema,S.cfg);

[result,~,state] = runWalkForwardOptimization( ...
    "ORB","REALISTIC",S.data,grid,plan, ...
    "Expectancy (R)",70,factory,[],struct(),false);

assert(state.completed_windows==height(plan.windows));
assert(height(result.aggregate_results)==2);
assert(all(result.aggregate_results.windows_evaluated==height(plan.windows)));
assert(result.holdout.status=="LOCKED");

fprintf("TEST ORB WALK FORWARD SMOKE SUPERADO\n");
disp(result.aggregate_results(:,{ ...
    'parameter_1_value','mean_oos_expectancy_r', ...
    'worst_oos_expectancy_r','plateau_score'}));

function runner = createRunner(slice,phase,windowId,schema,cfg) %#ok<INUSD>
prepared = prepareStrategyOptimization( ...
    "ORB",slice,cfg,schema);
runner = @(parameterSet) ...
    runStrategyOptimizationCombination( ...
        "ORB",slice,cfg,parameterSet, ...
        "REALISTIC",70,prepared);
end
