clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

source = fileread(fullfile( ...
    matlabRoot,"Dashboard","launchQuantLabDashboard.m"));

requiredCoreCalls = [ ...
    "updateResearchKPIBar("; ...
    "updateEquityCharts("; ...
    "updateVolumeChart("; ...
    "updateDrawdownChart("; ...
    "updateExposureChart("; ...
    "updateTurnoverChart("; ...
    "updateOrdersTable("; ...
    "updateTradesTable("];

for i = 1:numel(requiredCoreCalls)
    assert(contains(source,requiredCoreCalls(i)), ...
        "Falta componente principal: %s", ...
        requiredCoreCalls(i));
end

assert(contains(source, ...
    "profileDropdown.Enable = ""off"""));

assert(contains(source, ...
    "profileDropdown.Enable = ""on"""));

assert(contains(source, ...
    "finishCoreRefresh()"));

fprintf("TEST DASHBOARD CORE PROFILE REFRESH SUPERADO\n");
