clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
source = fileread(fullfile( ...
    matlabRoot,"Dashboard","launchQuantLabDashboard.m"));

startupSection = extractBetween( ...
    source, ...
    "isInitializingDashboard = true;", ...
    "app = struct(");

assert(contains(startupSection,"refreshAll();"));
assert(contains(startupSection, ...
    "dashboardState.isStartupRefresh = false;"));
assert(~contains(startupSection, ...
    "drawnow nocallbacks;"), ...
    "Startup must not force a blocking graphics synchronization.");

assert(contains(source, ...
    '"isStartupRefresh",true'));
assert(contains(source, ...
    "if ~dashboardState.isStartupRefresh"));

assert(~contains(startupSection, ...
    "updateOptimizationDashboard("));
assert(~contains(startupSection, ...
    "updateWalkForwardDashboard("));

fprintf("TEST DASHBOARD STARTUP VISIBLE CORE ONLY SUPERADO\n");
