clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

chartFile = fullfile( ...
    matlabRoot, ...
    "Dashboard", ...
    "Components", ...
    "plotTradeSessionChart.m");

source = fileread(chartFile);

assert(contains(source, ...
    '[entryTime exitTime]'), ...
    "La conexión no usa los tiempos exactos.");

assert(contains(source, ...
    '[entryPrice exitPrice]'), ...
    "La conexión no usa los precios exactos.");

assert(contains(source, ...
    '"Color",[0.25 0.25 0.25]'), ...
    "La conexión no usa gris oscuro.");

assert(contains(source, ...
    '"LineWidth",0.75'), ...
    "La conexión no mantiene un grosor fino.");

connectionBlock = extractBetween( ...
    source, ...
    "plot(ax, ..." + newline + ...
    "    [entryTime exitTime],", ...
    '"HandleVisibility","off");');

assert(~isempty(connectionBlock));
assert(contains(connectionBlock(1),'":"'), ...
    "La conexión no usa línea de puntos.");

fprintf("TEST TRADE RESEARCH DOTTED CONNECTION SUPERADO\n");
