clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
contextSource = fileread(fullfile( ...
    matlabRoot,"Strategies","CRT3H","buildCRT3HContext.m"));
scenarioSource = fileread(fullfile( ...
    matlabRoot,"Strategies","CRT3H","runCRT3HScenario.m"));
pluginSource = fileread(fullfile( ...
    matlabRoot,"Strategies","CRT3H","runCRT3HPlugin.m"));

assert(contains(contextSource,"dayFirstIndex = find(isNewDay)"));
assert(contains(contextSource,"dayLastIndex ="));
assert(contains(contextSource, ...
    "windows = repmat(emptyWindow(data,cfg),2*numel(days),1)"));
assert(contains(contextSource, ...
    "dayIndices = (dayFirstIndex(i):dayLastIndex(i))'"));
assert(contains(contextSource,"dayTimes = data.datetime_local(dayIndices)"));
assert(~contains(contextSource, ...
    "find(data.datetime_local>=w.ref_start"), ...
    "No se debe buscar cada ventana sobre todo el histórico.");
assert(~contains(contextSource, ...
    "rows = windows([windows.session_date]==days(i))"), ...
    "La tabla diaria no debe volver a recorrer todas las ventanas.");

assert(contains(scenarioSource, ...
    "if ~all(ismember(required,string(data.Properties.VariableNames)))"));
assert(contains(scenarioSource,"london = windows(2*i-1)"));
assert(contains(scenarioSource,"newYork = windows(2*i)"));
assert(~contains(scenarioSource,"function w = getWindow"), ...
    "Cada escenario debe reutilizar el orden de ventanas ya validado.");
assert(contains(pluginSource,"[%02d/%02d]"));
assert(contains(pluginSource,"escenarios completados en %.1f s"));

fprintf("TEST CRT3H FAST CONTEXT INDEXING SUPERADO\n");
