clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
source = fileread(fullfile( ...
    matlabRoot,"Dashboard","launchQuantLabDashboard.m"));

assert(contains(source,"function updateOptimizationEstimate()"));
assert(contains(source,"optimizationEstimateLabel"));
assert(contains(source,"optimizationEstimateDetailLabel"));
assert(contains(source,"countSweepValues("));
assert(contains(source, ...
    '"%d × %d parameter values = %d configurations"'));

requiredCallbacks = [ ...
    "optimizationStart1Field.ValueChangedFcn"; ...
    "optimizationStop1Field.ValueChangedFcn"; ...
    "optimizationStep1Field.ValueChangedFcn"; ...
    "optimizationStart2Field.ValueChangedFcn"; ...
    "optimizationStop2Field.ValueChangedFcn"; ...
    "optimizationStep2Field.ValueChangedFcn"; ...
    "optimizationLimitField.ValueChangedFcn"];

for callback = requiredCallbacks'
    assert(contains(source,callback));
end

fprintf("TEST FULL GRID DYNAMIC ESTIMATE SUPERADO\n");
