clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

dashboardFile = fullfile( ...
    matlabRoot, ...
    "Dashboard", ...
    "launchQuantLabDashboard.m");

source = fileread(dashboardFile);

assert(contains(source, ...
    "ordersTable.CellSelectionCallback"), ...
    "La tabla Orders no tiene callback de selección.");

assert(contains(source, ...
    "function selectOrdersRow(event)"), ...
    "Falta el callback selectOrdersRow.");

ordersFunction = extractBetween( ...
    source, ...
    "function selectOrdersRow(event)", ...
    "function selectResearchTrade(event)");

assert(~isempty(ordersFunction), ...
    "No se pudo localizar el callback de Orders.");

assert(contains(ordersFunction(1), ...
    "highlightTradeTableRow("), ...
    "Orders no resalta la fila completa.");

assert(contains(ordersFunction(1), ...
    "ordersTable"), ...
    "El resaltado no se aplica a la tabla Orders.");

assert(contains(ordersFunction(1), ...
    "drawnow;"), ...
    "Orders no fuerza el repintado inmediato.");

fprintf("TEST ORDERS TABLE IMMEDIATE HIGHLIGHT SUPERADO\n");
