clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

request = table( ...
    ["alpha";"beta"], ...
    ["Alpha";"Beta"], ...
    ["numeric";"integer"], ...
    [1;10], ...
    [3;20], ...
    [1;10], ...
    'VariableNames',{ ...
    'name','label','type', ...
    'start_value','stop_value','step_value'});

grid = buildParameterSweepGrid(request,20);
assert(height(grid)==6);

global QUANTLAB_SWEEP_TEST_CALLS;
QUANTLAB_SWEEP_TEST_CALLS = 0;

runner = @mockRunner;
cache = containers.Map( ...
    "KeyType","char","ValueType","any");

callbacks = struct( ...
    "progress",@(completed,total,row) ...
        assert(completed<=total), ...
    "cancel",@() false);

[results,cache,state] = runParameterSweep( ...
    "MOCK","REALISTIC",70,grid, ...
    runner,cache,callbacks);

assert(height(results)==6);
assert(state.completed==6);
assert(~state.cancelled);
assert(QUANTLAB_SWEEP_TEST_CALLS==6);
assert(all(results.status=="OK"));

[resultsCached,cache,stateCached] = runParameterSweep( ...
    "MOCK","REALISTIC",70,grid, ...
    runner,cache,callbacks);

assert(height(resultsCached)==6);
assert(stateCached.completed==6);
assert(QUANTLAB_SWEEP_TEST_CALLS==6, ...
    "La segunda ejecución debía usar la caché.");
assert(all(resultsCached.from_cache));

fprintf("TEST GENERIC PARAMETER SWEEP ENGINE SUPERADO\n");

function metrics = mockRunner(parameterSet)
global QUANTLAB_SWEEP_TEST_CALLS;
QUANTLAB_SWEEP_TEST_CALLS = ...
    QUANTLAB_SWEEP_TEST_CALLS+1;

alpha = parameterSet.value( ...
    parameterSet.name=="alpha");
beta = parameterSet.value( ...
    parameterSet.name=="beta");

metrics = createEmptyOptimizationMetrics();
metrics.status = "OK";
metrics.executed_trades = 100;
metrics.win_rate_pct = 52;
metrics.net_r = alpha + beta/10;
metrics.net_pnl_usd = 100*metrics.net_r;
metrics.return_pct = metrics.net_pnl_usd/500;
metrics.profit_factor = 1.20 + alpha/100;
metrics.expectancy_r = metrics.net_r/100;
metrics.max_drawdown_pct = 5 + beta/100;
metrics.final_equity_usd = ...
    50000+metrics.net_pnl_usd;
metrics.is_count = 70;
metrics.is_expectancy_r = ...
    metrics.expectancy_r*1.10;
metrics.oos_count = 30;
metrics.oos_expectancy_r = ...
    metrics.expectancy_r*0.90;
metrics.return_drawdown_ratio = ...
    metrics.return_pct/metrics.max_drawdown_pct;
metrics.robustness_score = ...
    min(metrics.is_expectancy_r, ...
        metrics.oos_expectancy_r) - ...
    0.5*abs( ...
        metrics.is_expectancy_r - ...
        metrics.oos_expectancy_r);
metrics.stable_sign = "YES";
end
