clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
source = fileread(fullfile( ...
    matlabRoot,"Dashboard","launchQuantLabDashboard.m"));

assert(contains(source, ...
    'wfStatusRow = uigridlayout(walkForwardControls,[1 3])'));
assert(contains(source, ...
    'wfStatusRow.ColumnWidth = {"1x",165,430}'));
assert(contains(source,"wfEstimateDetailLabel"));
assert(contains(source, ...
    '"%d windows × %d configurations × 2 phases%s"'));

executionSection = extractBetween( ...
    source, ...
    "% Row 4 — ranking and execution", ...
    "% Row 5 — status and estimate");

assert(~contains(executionSection,"wfEstimateLabel"), ...
    "Estimated runs must not share the crowded execution row.");

fprintf("TEST WALK FORWARD ESTIMATE FULL WIDTH SUPERADO\n");
