clear;
clc;

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(matlabRoot));

equitySource = fileread(fullfile( ...
    matlabRoot,"Dashboard","Components", ...
    "updateEquityCharts.m"));

drawdownSource = fileread(fullfile( ...
    matlabRoot,"Dashboard","Components", ...
    "updateDrawdownChart.m"));

dashboardSource = fileread(fullfile( ...
    matlabRoot,"Dashboard", ...
    "launchQuantLabDashboard.m"));

assert(contains(equitySource,"positiveEquity"));
assert(contains(equitySource,"negativeEquity"));
assert(contains(equitySource,'"FaceColor",greenFill'));
assert(contains(equitySource,'"FaceColor",redFill'));
assert(contains(equitySource,'ylabel(equityAxes,"Equity (%)")'));

assert(contains(drawdownSource, ...
    "ylim(drawdownAxes,[lowerLimit 0])"), ...
    "Drawdown no fija 0 %% como límite superior.");

assert(contains(dashboardSource, ...
    "gVolume = uigridlayout(pVolume,[1 1])"), ...
    "Assets Sales Volume no usa layout responsivo.");

assert(contains(dashboardSource, ...
    "gDrawdown = uigridlayout(pDD,[1 1])"), ...
    "Drawdown no usa layout responsivo.");

fprintf("TEST DASHBOARD EQUITY DRAWDOWN LAYOUT SUPERADO\n");
