function capabilities = buildTemplateBarAnalysisCapabilities()
capabilities = struct( ...
    "calendar_analytics",true, ...
    "trade_distribution",true, ...
    "segment_explorer",true, ...
    "parameter_sweep",false, ...
    "walk_forward",false, ...
    "mfe_mae",false, ...
    "intraday_replay",true);
end
