function schema = buildCRT3HParameterSchema()
%BUILDCRT3HPARAMETERSCHEMA Parámetros propios del plugin.

schema = table( ...
    ["crt3h.entryFraction"; ...
     "crt3h.rewardRisk"; ...
     "crt3h.breakEven.enabled"; ...
     "crt3h.breakEven.triggerR"; ...
     "crt3h.breakEven.offsetTicks"; ...
     "crt3h.exitManagement.trailing.activationR"; ...
     "crt3h.exitManagement.trailing.targetStepR"; ...
     "crt3h.exitManagement.trailing.swingLeftBars"; ...
     "crt3h.exitManagement.trailing.swingRightBars"; ...
     "crt3h.exitManagement.trailing.swingOffsetTicks"; ...
     "crt3h.london.thresholdPoints"; ...
     "crt3h.newYork.thresholdPoints"; ...
     "crt3h.enableLondon"; ...
     "crt3h.enableNewYork"; ...
     "crt3h.blockNyAfterLondonTP"], ...
    ["CRT Entry Fraction"; ...
     "CRT Target R Multiple"; ...
     "Enable Break-Even"; ...
     "Break-Even Trigger"; ...
     "Break-Even Offset"; ...
     "Trailing Activation"; ...
     "Target Stair Step"; ...
     "Swing Left Bars"; ...
     "Swing Right Bars"; ...
     "Swing Stop Offset"; ...
     "London Sweep Threshold"; ...
     "New York Sweep Threshold"; ...
     "Enable London"; ...
     "Enable New York"; ...
     "Block NY after London TP"], ...
    ["numeric";"numeric";"integer";"numeric";"integer"; ...
     "numeric";"numeric";"integer";"integer";"integer"; ...
     "numeric";"numeric";"integer";"integer";"integer"], ...
    [0.75;0.5;1;1.0;0;1.5;0.5;2;2;1;0.25;0.25;1;1;1], ...
    [0.50;0.25;0;0.25;0;0.5;0.25;1;1;0;0;0;0;0;0], ...
    [0.90;5;1;4.75;8;5;2;10;10;8;20;20;1;1;1], ...
    [0.025;0.25;1;0.25;1;0.25;0.25;1;1;1;0.25;0.25;1;1;1], ...
    [0.50;0.25;0;0.5;0;1;0.25;1;1;0;0.25;0.25;0;0;0], ...
    [0.80;3;1;3;2;3;1;4;4;2;4;4;1;1;1], ...
    ["fraction";"R";"boolean";"R";"ticks";"R";"R"; ...
     "bars";"bars";"ticks";"points";"points"; ...
     "boolean";"boolean";"boolean"], ...
    true(15,1),true(15,1),false(15,1), ...
    ["Progress from swept extreme toward opposite CRT extreme"; ...
     "Profit target expressed in initial risk multiples"; ...
     "Move the protective stop after a favorable excursion"; ...
     "Favorable excursion in initial R that activates break-even"; ...
     "Ticks locked beyond the exact entry price"; ...
     "Initial R milestone that activates structural trailing"; ...
     "R increment applied to each virtual target milestone"; ...
     "Bars required to the left of a confirmed swing"; ...
     "Bars required to the right of a confirmed swing"; ...
     "Ticks placed beyond the confirmed swing"; ...
     "Minimum penetration below the London CRT low or above its high"; ...
     "Minimum penetration below the New York CRT low or above its high"; ...
     "Allow London setups"; ...
     "Allow New York setups"; ...
     "Do not trade New York after a London target"], ...
    'VariableNames',{ ...
    'name','label','type','default_value','minimum','maximum', ...
    'step','sweep_start','sweep_stop','unit','enabled', ...
    'optimizable','rebuild_events','description'});

schema = normalizeParameterSchema(schema);
end
