function catalog = buildCRT3HFeatureCatalog()
%BUILDCRT3HFEATURECATALOG Variables disponibles para Research.

rows = { ...
    "session_name","CRT Session","categorical","","input", ...
        "Categories",true,"CRT_3H","London or New York"; ...
    "direction","Direction","categorical","","input", ...
        "Categories",true,"CRT_3H","Direction fixed by first sweep"; ...
    "sweep_side","Sweep Side","categorical","","input", ...
        "Categories",true,"CRT_3H","Swept CRT extreme"; ...
    "crt_range_points","CRT Range","numeric","points","context", ...
        "Quintiles",true,"CRT_3H","Three-hour reference range"; ...
    "manipulation_points","Manipulation Size","numeric","points", ...
        "context","Quintiles",true,"CRT_3H","Distance beyond CRT extreme"; ...
    "entry_fraction","Entry Fraction","numeric","fraction","input", ...
        "Categories",true,"CRT_3H","Progress from sweep toward opposite CRT"; ...
    "entry_level","Configured Entry Level","numeric","price","input", ...
        "Quintiles",true,"CRT_3H","Frozen stop-entry trigger"; ...
    "reward_risk_planned","Planned Target","numeric","R","input", ...
        "Categories",true,"CRT_3H","Target distance in initial R"; ...
    "risk_points","Initial Risk","numeric","points","input", ...
        "Quintiles",true,"CRT_3H","Entry-to-manipulation risk"; ...
    "threshold_points","Sweep Threshold","numeric","points","input", ...
        "Categories",true,"CRT_3H","Required penetration beyond range"; ...
    "day_of_week","Day of Week","categorical","","context", ...
        "Categories",true,"derived","Derived from session date"; ...
    "entry_hour","Entry Hour","numeric","hour","context", ...
        "Categories",true,"derived","Derived from entry timestamp"};

catalog = cell2table(rows, ...
    'VariableNames',{ ...
    'name','label','type','unit','role', ...
    'default_grouping','enabled','source','description'});
catalog = normalizeFeatureCatalog(catalog);
end
