function capabilities = buildCRT3HAnalysisCapabilities()
capabilities = struct( ...
    "calendar_analytics",true, ...
    "trade_distribution",true, ...
    "segment_explorer",true, ...
    "parameter_sweep",true, ...
    "walk_forward",true, ...
    "mfe_mae",true, ...
    "intraday_replay",true);
end
