function event = makeEvent(eventType, eventTime, sessionDate, symbol, ...
    barIndex, price, direction, source, payload)
%MAKEEVENT Construye una fila de evento con el esquema estándar.

arguments
    eventType (1,1) string
    eventTime (1,1) datetime
    sessionDate (1,1) datetime
    symbol (1,1) string
    barIndex (1,1) double = 0
    price (1,1) double = NaN
    direction (1,1) string = ""
    source (1,1) string = ""
    payload = struct()
end

event = table( ...
    eventType, ...
    eventTime, ...
    sessionDate, ...
    symbol, ...
    barIndex, ...
    price, ...
    direction, ...
    source, ...
    {payload}, ...
    'VariableNames', { ...
    'event_type','event_time','session_date','symbol', ...
    'bar_index','price','direction','source','payload'});
end
