function validateStrategyResults(results,cfg,plugin)
%VALIDATESTRATEGYRESULTS Valida escenarios y trades del plugin.

if ~isstruct(results)
    error("QuantLab:StrategyResultsType", ...
        "plugin.run debe devolver una estructura.");
end

profiles = string({cfg.executionProfiles.name});

for profile = profiles
    field = matlab.lang.makeValidName(upper(profile));
    if ~isfield(results,field)
        error("QuantLab:StrategyProfileMissing", ...
            "%s no devolvió el perfil %s.",plugin.name,profile);
    end

    scenario = results.(field);
    if ~isstruct(scenario) || ...
            ~isfield(scenario,"trades") || ...
            ~isfield(scenario,"summary") || ...
            ~istable(scenario.trades)
        error("QuantLab:StrategyScenarioContract", ...
            "%s/%s no cumple Scenario v1.",plugin.name,profile);
    end

    validateStrategyTradeTable( ...
        scenario.trades,plugin.name,profile);

    if isfield(scenario,"sessionScenarios") && ...
            isstruct(scenario.sessionScenarios)
        sessionFields = string(fieldnames(scenario.sessionScenarios));
        for sessionField = sessionFields'
            sessionScenario = ...
                scenario.sessionScenarios.(sessionField);
            if ~isstruct(sessionScenario) || ...
                    ~isfield(sessionScenario,"trades") || ...
                    ~isfield(sessionScenario,"summary") || ...
                    ~istable(sessionScenario.trades)
                error("QuantLab:StrategySessionScenarioContract", ...
                    "%s/%s/%s no cumple Scenario v1.", ...
                    plugin.name,profile,sessionField);
            end
            validateStrategyTradeTable( ...
                sessionScenario.trades,plugin.name, ...
                profile + "_" + sessionField);

            if isfield(sessionScenario,"exitManagementScenarios") && ...
                    isstruct(sessionScenario.exitManagementScenarios)
                exitFields = string(fieldnames( ...
                    sessionScenario.exitManagementScenarios));
                for exitField = exitFields'
                    exitScenario = ...
                        sessionScenario.exitManagementScenarios.(exitField);
                    if ~isstruct(exitScenario) || ...
                            ~isfield(exitScenario,"trades") || ...
                            ~isfield(exitScenario,"summary") || ...
                            ~istable(exitScenario.trades)
                        error("QuantLab:StrategyExitScenarioContract", ...
                            "%s/%s/%s/%s no cumple Scenario v1.", ...
                            plugin.name,profile,sessionField,exitField);
                    end
                    validateStrategyTradeTable( ...
                        exitScenario.trades,plugin.name, ...
                        profile + "_" + sessionField + "_" + exitField);
                end
            end
        end
    end
end

if ~isfield(results,"summaryTable") || ~istable(results.summaryTable)
    error("QuantLab:StrategySummaryTable", ...
        "%s debe devolver results.summaryTable.",plugin.name);
end
end
