function trade = createEmptyTradeRecord(cfg,profileName)
%CREATEEMPTYTRADERECORD Contrato Trade v1 común a estrategias de barras.

spec = normalizeInstrumentSpec(cfg);
tz = char(spec.marketTimezone);

trade = struct( ...
    "valid",false, ...
    "record_type","SESSION_AUDIT", ...
    "setup_status","NOT_EVALUATED", ...
    "order_status","NOT_CREATED", ...
    "profile",string(profileName), ...
    "symbol",spec.symbol, ...
    "asset_class",spec.assetClass, ...
    "session_date",NaT("TimeZone",tz), ...
    "direction","", ...
    "signal_name","", ...
    "rules_version","", ...
    "order_time",NaT("TimeZone",tz), ...
    "order_price",NaN, ...
    "entry_fraction",NaN, ...
    "entry_level",NaN, ...
    "entry_level_50",NaN, ...
    "reward_risk_planned",NaN, ...
    "entry_time",NaT("TimeZone",tz), ...
    "exit_time",NaT("TimeZone",tz), ...
    "entry_price_raw",NaN, ...
    "entry_price",NaN, ...
    "stop_price",NaN, ...
    "initial_stop_price",NaN, ...
    "target_price",NaN, ...
    "exit_management","FIXED_TARGET", ...
    "trailing_enabled",false, ...
    "trailing_activation_r",NaN, ...
    "trailing_activation_price",NaN, ...
    "trailing_target_step_r",NaN, ...
    "trailing_swing_left_bars",NaN, ...
    "trailing_swing_right_bars",NaN, ...
    "trailing_swing_offset_ticks",NaN, ...
    "trailing_activated",false, ...
    "trailing_activation_time",NaT("TimeZone",tz), ...
    "trailing_stop_triggered",false, ...
    "trailing_stop_price",NaN, ...
    "trailing_stop_effective_time",NaT("TimeZone",tz), ...
    "target_steps_advanced",0, ...
    "final_target_r",NaN, ...
    "final_target_price",NaN, ...
    "trailing_stop_times","", ...
    "trailing_stop_prices","", ...
    "target_step_times","", ...
    "target_step_prices","", ...
    "break_even_enabled",false, ...
    "break_even_trigger_r",NaN, ...
    "break_even_trigger_price",NaN, ...
    "break_even_price",NaN, ...
    "break_even_triggered",false, ...
    "break_even_trigger_time",NaT("TimeZone",tz), ...
    "break_even_effective_time",NaT("TimeZone",tz), ...
    "exit_price",NaN, ...
    "risk_points",NaN, ...
    "risk_budget_usd",NaN, ...
    "risk_per_quantity_usd",NaN, ...
    "risk_per_contract_usd",NaN, ...
    "quantity",0, ...
    "contracts",0, ...
    "effective_risk_usd",0, ...
    "gross_points",NaN, ...
    "gross_R",NaN, ...
    "net_R",NaN, ...
    "gross_pnl_usd",NaN, ...
    "commission_usd",NaN, ...
    "net_pnl_usd",NaN, ...
    "equity_before_usd",NaN, ...
    "equity_after_usd",NaN, ...
    "exit_reason","", ...
    "skip_reason","", ...
    "bars_held",NaN, ...
    "mfe_points",NaN, ...
    "mae_points",NaN, ...
    "mfe_R",NaN, ...
    "mae_R",NaN);
end
