function profile = createExecutionProfile( ...
    name,entrySlip,stopSlip,targetSlip,commissionRT,sameBarPolicy)
%CREATEEXECUTIONPROFILE Perfil compatible y extensible.

profile = struct( ...
    "name",string(name), ...
    "entrySlippagePoints",entrySlip, ...
    "stopSlippagePoints",stopSlip, ...
    "targetSlippagePoints",targetSlip, ...
    "commissionRoundTripUSDPerContract",commissionRT, ...
    "sameBarPolicy",string(sameBarPolicy), ...
    "slippageModel",struct( ...
        "type","FIXED_PRICE", ...
        "entry",entrySlip, ...
        "stop",stopSlip, ...
        "target",targetSlip, ...
        "eod",entrySlip), ...
    "commissionModel",struct( ...
        "type","PER_QUANTITY_ROUND_TRIP", ...
        "amount",commissionRT), ...
    "spreadModel",struct("type","NONE","amount",0));
end
