function cfg = loadQuantLabConfig(matlabRoot,instrument,strategyName)
arguments
    matlabRoot (1,1) string = ...
        string(fileparts(fileparts(mfilename('fullpath'))))
    instrument (1,1) string = "MNQ"
    strategyName (1,1) string = "CRT_3H_MADRID"
end

instrumentDef = getQuantLabInstrumentDefinition(instrument);
cfg = struct();
cfg.matlabRoot = matlabRoot;
cfg.quantLabRoot = string(fileparts(matlabRoot));
cfg.strategyName = upper(strtrim(strategyName));
cfg.dataLoader = "QUANTLAB_IBKR_CSV";

isCRT3H = upper(string(cfg.strategyName))=="CRT_3H_MADRID";
isSessionRange = upper(string(cfg.strategyName))== ...
    "SESSION_RANGE_MADRID";
usesExtendedData = isCRT3H || isSessionRange;

if usesExtendedData
    cfg.dataFile = fullfile(cfg.quantLabRoot,"data",instrumentDef.symbol, ...
        "1_min",instrumentDef.symbol + "_CONTFUT_1_min_ALL.csv");
else
    cfg.dataFile = fullfile(cfg.quantLabRoot,"data",instrumentDef.symbol, ...
        "1_min",instrumentDef.symbol + "_CONTFUT_1_min_RTH.csv");
end

cfg.instrument = instrumentDef.symbol;
cfg.exchange = instrumentDef.exchange;
cfg.expectedBarMinutes = 1;

if usesExtendedData
    cfg.marketTimezone = "Europe/Madrid";
    cfg.sessionStart = duration(0,0,0);
    cfg.sessionEnd = duration(24,0,0);
    cfg.expectedBarsPerFullSession = 0;
    cfg.sessionSpec = createSessionSpec( ...
        name=instrumentDef.symbol + " Extended - Madrid", ...
        timezone=cfg.marketTimezone, ...
        mode="24X7", ...
        startTime=cfg.sessionStart, ...
        endTime=cfg.sessionEnd, ...
        expectedBarMinutes=cfg.expectedBarMinutes, ...
        expectedBarsPerSession=cfg.expectedBarsPerFullSession, ...
        weekdays=1:7);
    sessionTemplate = "US_FUTURES_EXTENDED_MADRID";
else
    cfg.marketTimezone = "America/New_York";
    cfg.sessionStart = duration(9,30,0);
    cfg.sessionEnd = duration(16,0,0);
    cfg.expectedBarsPerFullSession = 390;
    cfg.sessionSpec = createSessionSpec( ...
        name="US RTH", ...
        timezone=cfg.marketTimezone, ...
        mode="REGULAR", ...
        startTime=cfg.sessionStart, ...
        endTime=cfg.sessionEnd, ...
        expectedBarMinutes=cfg.expectedBarMinutes, ...
        expectedBarsPerSession=cfg.expectedBarsPerFullSession, ...
        weekdays=2:6);
    sessionTemplate = "US_RTH";
end

cfg.instrumentSpec = createInstrumentSpec( ...
    instrumentDef.symbol,"FUTURE", ...
    quoteCurrency="USD", ...
    accountCurrency="USD", ...
    tickSize=instrumentDef.tickSize, ...
    contractMultiplier=instrumentDef.contractMultiplier, ...
    quantityStep=1, ...
    minimumQuantity=1, ...
    maximumQuantity=instrumentDef.maximumQuantity, ...
    marketTimezone=cfg.marketTimezone, ...
    sessionTemplate=sessionTemplate);

cfg.removeDuplicates = true;
cfg.requireSortedData = true;
cfg.filterToSession = ~usesExtendedData;
cfg.rejectNonPositivePrices = true;
cfg.rejectNegativeVolume = true;

cfg.orbStart = duration(9,30,0);
cfg.orbEnd = duration(9,35,0);
cfg.orb = struct("rewardRisk",10.0, ...
    "tradeDoji",false,"requireFullSession",true, ...
    "filters",struct( ...
        "minimumRangePoints",0, ...
        "maximumRangePoints",Inf));

cfg.emaCross = struct( ...
    "fastPeriod",10, ...
    "slowPeriod",30, ...
    "atrPeriod",14, ...
    "atrStopMultiple",1.5, ...
    "rewardRisk",2.0, ...
    "entryStart",duration(9,45,0), ...
    "entryEnd",duration(15,30,0), ...
    "allowLong",true, ...
    "allowShort",true, ...
    "maximumTradesPerSession",2, ...
    "requireFullSession",true);

cfg.crt3h = struct( ...
    "entryFraction",0.75, ...
    "rulesVersion","CRT3H_ENTRY_075_RR_050", ...
    "enableLondon",true, ...
    "enableNewYork",true, ...
    "blockNyAfterLondonTP",true, ...
    "allowExitOnEntryBar",false, ...
    "rewardRisk",0.5, ...
    "breakEven",struct( ...
        "enabled",true, ...
        "triggerR",1.0, ...
        "offsetTicks",0, ...
        "activateOnNextBar",true), ...
    "exitManagement",struct( ...
        "mode","FIXED_TARGET", ...
        "trailing",struct( ...
            "enabled",true, ...
            "activationR",1.5, ...
            "targetStepR",0.5, ...
            "swingLeftBars",2, ...
            "swingRightBars",2, ...
            "swingOffsetTicks",1, ...
            "activateOnNextBar",true)), ...
    "london",struct( ...
        "refStart",duration(6,0,0), ...
        "refEnd",duration(9,0,0), ...
        "entryStart",duration(9,0,0), ...
        "manEnd",duration(11,0,0), ...
        "thresholdPoints",instrumentDef.tickSize), ...
    "newYork",struct( ...
        "refStart",duration(12,0,0), ...
        "refEnd",duration(15,0,0), ...
        "entryStart",duration(15,0,0), ...
        "manEnd",duration(17,0,0), ...
        "thresholdPoints",instrumentDef.tickSize));

if isSessionRange
    % Variante independiente: comparte el motor de sweep, stop, riesgo y
    % perfiles con CRT_3H_MADRID, pero congela su propia geometría 60/0,66R.
    cfg.crt3h.referenceMode = "SESSION_RANGES";
    cfg.crt3h.entryFraction = 0.60;
    cfg.crt3h.rewardRisk = 0.66;
    cfg.crt3h.rulesVersion = ...
        "SESSION_RANGE_ASIA_0000_0900_LONDON_0900_1500_ENTRY_060_RR_066";
    cfg.crt3h.signalPrefix = "SESSION_RANGE";
    cfg.crt3h.london = struct( ...
        "refStart",duration(0,0,0), ...
        "refEnd",duration(9,0,0), ...
        "entryStart",duration(9,0,0), ...
        "manEnd",duration(11,0,0), ...
        "thresholdPoints",instrumentDef.tickSize);
    cfg.crt3h.newYork = struct( ...
        "refStart",duration(9,0,0), ...
        "refEnd",duration(15,0,0), ...
        "entryStart",duration(15,0,0), ...
        "manEnd",duration(17,0,0), ...
        "thresholdPoints",instrumentDef.tickSize);
    cfg.crt3h.newYorkRangeOrder = ["ASIA","LONDRES"];
end

% Las cuatro políticas de sesión se ejecutan como backtests independientes.
% Cada una mantiene su propia equity y, por tanto, su propio sizing al 1 %.
cfg.crt3h.defaultSessionScenario = ...
    "LONDON_TP_BLOCKS_NEW_YORK";
cfg.crt3h.sessionScenarios = [ ...
    struct("name","LONDON_ONLY", ...
        "displayName","Solo Londres", ...
        "enableLondon",true, ...
        "enableNewYork",false, ...
        "blockNyAfterLondonTP",false), ...
    struct("name","NEW_YORK_ONLY", ...
        "displayName","Solo Nueva York", ...
        "enableLondon",false, ...
        "enableNewYork",true, ...
        "blockNyAfterLondonTP",false), ...
    struct("name","LONDON_AND_NEW_YORK", ...
        "displayName","Londres + Nueva York", ...
        "enableLondon",true, ...
        "enableNewYork",true, ...
        "blockNyAfterLondonTP",false), ...
    struct("name","LONDON_TP_BLOCKS_NEW_YORK", ...
        "displayName","Londres + NY; TP Londres bloquea NY", ...
        "enableLondon",true, ...
        "enableNewYork",true, ...
        "blockNyAfterLondonTP",true)];

% Las dos gestiones de salida se ejecutan de forma independiente. La
% variante trailing no liquida en cada escalón: 1,5R pasa a 2R, después a
% 2,5R, etc., y la salida real se produce por el stop estructural.
cfg.crt3h.defaultExitManagementScenario = ...
    "FIXED_TARGET";
cfg.crt3h.exitManagementScenarios = [ ...
    struct("name","FIXED_TARGET", ...
        "displayName","TP fijo 0,5R", ...
        "mode","FIXED_TARGET"), ...
    struct("name","SWING_TRAILING_STEP_TARGET", ...
        "displayName","TP escalonado + trailing swing", ...
        "mode","SWING_TRAILING_STEP_TARGET")];

if isSessionRange
    cfg.crt3h.exitManagementScenarios(1).displayName = ...
        "TP fijo 0,66R";
end

cfg.risk = struct("mode","PERCENT_EQUITY", ...
    "initialEquityUSD",50000,"fixedRiskUSD",100, ...
    "percentRisk",0.01,"minimumQuantity",1, ...
    "maximumQuantity",instrumentDef.maximumQuantity,"minimumContracts",1, ...
    "maximumContracts",instrumentDef.maximumQuantity, ...
    "insufficientRiskPolicy","SKIP");

% El deslizamiento se expresa en ticks equivalentes para que MNQ, MES y
% MYM reciban exactamente la misma hipótesis de ejecución.
tick = instrumentDef.tickSize;
cfg.executionProfiles = [ ...
    createExecutionProfile("IDEAL",0,0,0,0,"STOP_FIRST"), ...
    createExecutionProfile("REALISTIC",tick,2*tick,0,1.24,"STOP_FIRST"), ...
    createExecutionProfile("CONSERVATIVE",2*tick,4*tick,tick,1.50,"STOP_FIRST")];

cfg.detectors = struct();
cfg.detectors.swing = struct( ...
    "leftBars",2,"rightBars",2, ...
    "allowEqualHighs",false,"allowEqualLows",false);
end
