function displayTable = buildWalkForwardAggregateDisplayTable( ...
    aggregate,rankingMetric)
%BUILDWALKFORWARDAGGREGATEDISPLAYTABLE Tabla robusta sin exponentes.

if isempty(aggregate)
    displayTable = table();
    return;
end

[fieldName,direction] = ...
    getWalkForwardRankingDefinition(rankingMetric);

valid = ~isnan(aggregate.(fieldName));
validRows = aggregate(valid,:);
invalidRows = aggregate(~valid,:);

if ~isempty(validRows)
    validRows = sortrows(validRows,fieldName,direction);
end

ordered = [validRows;invalidRows];

rank = nan(height(ordered),1);
rank(1:height(validRows)) = (1:height(validRows))';

displayTable = table( ...
    formatPlainNumericColumn(rank,0,true), ...
    ordered.parameter_1_label, ...
    formatPlainNumericColumn(ordered.parameter_1_value,6,true), ...
    ordered.parameter_2_label, ...
    formatPlainNumericColumn(ordered.parameter_2_value,6,true), ...
    formatPlainNumericColumn(ordered.windows_evaluated,0,true), ...
    formatPlainNumericColumn(ordered.selection_count,0,true), ...
    ordered.activity_status, ...
    formatPlainNumericColumn( ...
        ordered.equivalent_configurations,0,true), ...
    formatPlainNumericColumn( ...
        ordered.effective_oos_windows,0,true), ...
    formatPlainNumericColumn( ...
        ordered.total_oos_target_exits,0,true), ...
    formatPlainNumericColumn( ...
        ordered.mean_train_expectancy_r,4,false), ...
    formatPlainNumericColumn( ...
        ordered.mean_oos_expectancy_r,4,false), ...
    formatPlainNumericColumn( ...
        ordered.std_oos_expectancy_r,4,false), ...
    formatPlainNumericColumn( ...
        ordered.worst_oos_expectancy_r,4,false), ...
    formatPlainNumericColumn(ordered.positive_oos_pct,2,false), ...
    formatPlainNumericColumn(ordered.sign_agreement_pct,2,false), ...
    formatPlainNumericColumn(ordered.total_oos_pnl_usd,2,false), ...
    formatPlainNumericColumn( ...
        ordered.mean_oos_drawdown_pct,4,false), ...
    formatPlainNumericColumn( ...
        ordered.mean_oos_return_drawdown,4,false), ...
    formatPlainNumericColumn( ...
        ordered.wf_robustness_score,4,false), ...
    formatPlainNumericColumn(ordered.neighbor_count,0,true), ...
    formatPlainNumericColumn(ordered.plateau_score,4,false), ...
    'VariableNames',{ ...
    'Rank','Parameter1','Value1','Parameter2','Value2', ...
    'Windows','Selected','Activity','Equivalent', ...
    'EffectiveOOSWindows','OOSTargetHits', ...
    'MeanISExpectancyR','MeanOOSExpectancyR', ...
    'StdOOSExpectancyR','WorstOOSExpectancyR', ...
    'PositiveOOSPct','SignAgreementPct','TotalOOSPnLUSD', ...
    'MeanOOSDrawdownPct','MeanOOSReturnDrawdown', ...
    'WFRobustness','Neighbors','PlateauScore'});
end
