function displayTable = buildWalkForwardWindowDisplayTable(windowResults)
%BUILDWALKFORWARDWINDOWDISPLAYTABLE Tabla legible sin notación científica.

if isempty(windowResults)
    displayTable = table();
    return;
end

configuration = strings(height(windowResults),1);

for i = 1:height(windowResults)
    configuration(i) = ...
        windowResults.parameter_1_label(i) + "=" + ...
        formatPlainNumber( ...
            windowResults.parameter_1_value(i),6,true);

    if strlength(windowResults.parameter_2_label(i))>0
        configuration(i) = configuration(i) + ", " + ...
            windowResults.parameter_2_label(i) + "=" + ...
            formatPlainNumber( ...
                windowResults.parameter_2_value(i),6,true);
    end
end

displayTable = table( ...
    windowResults.window_id, ...
    string(windowResults.train_start,"yyyy-MM-dd"), ...
    string(windowResults.train_end,"yyyy-MM-dd"), ...
    string(windowResults.validation_start,"yyyy-MM-dd"), ...
    string(windowResults.validation_end,"yyyy-MM-dd"), ...
    configuration, ...
    windowResults.status, ...
    formatPlainNumericColumn( ...
        windowResults.train_selection_metric,4,false), ...
    formatPlainNumericColumn( ...
        windowResults.train_expectancy_r,4,false), ...
    formatPlainNumericColumn( ...
        windowResults.validation_expectancy_r,4,false), ...
    formatPlainNumericColumn( ...
        windowResults.validation_net_pnl_usd,2,false), ...
    formatPlainNumericColumn( ...
        windowResults.validation_return_pct,4,false), ...
    formatPlainNumericColumn( ...
        windowResults.validation_profit_factor,4,false), ...
    formatPlainNumericColumn( ...
        windowResults.validation_max_drawdown_pct,4,false), ...
    windowResults.expectancy_sign_stable, ...
    'VariableNames',{ ...
    'Window','TrainStart','TrainEnd','OOSStart','OOSEnd', ...
    'SelectedConfiguration','Status','TrainMetric', ...
    'TrainExpectancyR','OOSExpectancyR','OOSPnLUSD', ...
    'OOSReturnPct','OOSProfitFactor','OOSMaxDrawdownPct', ...
    'StableSign'});
end
