function displayTable = buildSessionScenarioComparisonTable( ...
    summaryTable,executionProfile,exitManagementScenario)
%BUILDSESSIONSCENARIOCOMPARISONTABLE Compara las políticas Londres/NY.

arguments
    summaryTable table
    executionProfile (1,1) string
    exitManagementScenario (1,1) string = ""
end

required = [ ...
    "executionProfile","sessionScenarioLabel","executedTrades", ...
    "winningTrades","losingTrades","breakevenTrades", ...
    "winRatePct","netR","netPnLUSD","profitFactor", ...
    "expectancyR","maxDrawdownUSD","finalEquityUSD"];

if isempty(summaryTable) || ...
        ~all(ismember(required,string(summaryTable.Properties.VariableNames)))
    displayTable = table();
    return;
end

rows = summaryTable( ...
    string(summaryTable.executionProfile)==executionProfile,:);
if strlength(exitManagementScenario)>0 && ...
        ismember("exitManagementScenario", ...
        string(rows.Properties.VariableNames))
    rows = rows(string(rows.exitManagementScenario)== ...
        exitManagementScenario,:);
end
if isempty(rows)
    displayTable = table();
    return;
end

displayTable = table( ...
    string(rows.sessionScenarioLabel), ...
    rows.executedTrades, ...
    rows.winningTrades, ...
    rows.losingTrades, ...
    rows.breakevenTrades, ...
    rows.winRatePct, ...
    rows.netR, ...
    rows.netPnLUSD, ...
    rows.profitFactor, ...
    rows.expectancyR, ...
    rows.maxDrawdownUSD, ...
    rows.finalEquityUSD, ...
    'VariableNames',{ ...
    'Policy','Trades','Wins','Losses','BreakEven', ...
    'WinRatePct','NetR','NetPnLUSD','ProfitFactor', ...
    'ExpectancyR','MaxDrawdownUSD','FinalEquityUSD'});
end
