function summary = buildCalendarSummaryTable(calendar)
%BUILDCALENDARSUMMARYTABLE Construye las métricas del calendario.

labels = [ ...
    "Meses con datos"; ...
    "Meses positivos"; ...
    "Meses positivos (%)"; ...
    "Rentabilidad media mensual"; ...
    "Volatilidad mensual"; ...
    "Mejor mes"; ...
    "Peor mes"; ...
    "Mejor año"; ...
    "Peor año"];

values = strings(size(labels));

observations = calendar.monthlyObservations;

if isempty(observations)
    summary = table(labels,values, ...
        'VariableNames',{'Metric','Value'});
    return;
end

returns = observations.return_pct;
positiveMonths = sum(returns>0);
monthCount = numel(returns);

values(1) = string(monthCount);
values(2) = string(positiveMonths);
values(3) = sprintf("%.1f %%",100*positiveMonths/monthCount);
values(4) = sprintf("%.2f %%",mean(returns,"omitnan"));
values(5) = sprintf("%.2f %%",std(returns,"omitnan"));

[bestMonthValue,bestIndex] = max(returns);
[worstMonthValue,worstIndex] = min(returns);

values(6) = formatMonthObservation( ...
    observations(bestIndex,:),bestMonthValue);

values(7) = formatMonthObservation( ...
    observations(worstIndex,:),worstMonthValue);

if ~isempty(calendar.yearReturns)
    [bestYearValue,bestYearIndex] = max(calendar.yearReturns);
    [worstYearValue,worstYearIndex] = min(calendar.yearReturns);

    values(8) = sprintf( ...
        "%d: %.2f %%", ...
        calendar.years(bestYearIndex), ...
        bestYearValue);

    values(9) = sprintf( ...
        "%d: %.2f %%", ...
        calendar.years(worstYearIndex), ...
        worstYearValue);
end

summary = table(labels,values, ...
    'VariableNames',{'Metric','Value'});
end

function text = formatMonthObservation(row,value)
monthLabels = [ ...
    "Ene","Feb","Mar","Abr","May","Jun", ...
    "Jul","Ago","Sep","Oct","Nov","Dic"];

text = monthLabels(row.month) + " " + ...
    string(row.year) + ": " + ...
    string(sprintf("%.2f %%",value));
end
