function displayTable = buildOptimizationDisplayTable(results,metricName)
%BUILDOPTIMIZATIONDISPLAYTABLE Ordena y presenta resultados sin exponentes.

if isempty(results)
    displayTable = table();
    return;
end

[metricField,direction] = getOptimizationMetricDefinition(metricName);
valid = results.status=="OK";

validResults = results(valid,:);
errorResults = results(~valid,:);

if ~isempty(validResults)
    validResults = sortrows(validResults,metricField,direction);
end

ordered = [validResults;errorResults];

rank = nan(height(ordered),1);
rank(ordered.status=="OK") = ...
    (1:sum(ordered.status=="OK"))';

cached = repmat("NO",height(ordered),1);
cached(logical(ordered.from_cache)) = "YES";

displayTable = table( ...
    formatPlainNumericColumn(rank,0,true), ...
    ordered.parameter_1_label, ...
    formatPlainNumericColumn(ordered.parameter_1_value,6,true), ...
    ordered.parameter_2_label, ...
    formatPlainNumericColumn(ordered.parameter_2_value,6,true), ...
    ordered.status, ...
    ordered.activity_status, ...
    formatPlainNumericColumn( ...
        ordered.equivalent_configurations,0,true), ...
    formatPlainNumericColumn(ordered.target_exit_count,0,true), ...
    formatPlainNumericColumn(ordered.executed_trades,0,true), ...
    formatPlainNumericColumn(ordered.win_rate_pct,4,false), ...
    formatPlainNumericColumn(ordered.net_r,4,false), ...
    formatPlainNumericColumn(ordered.net_pnl_usd,2,false), ...
    formatPlainNumericColumn(ordered.return_pct,4,false), ...
    formatPlainNumericColumn(ordered.profit_factor,4,false), ...
    formatPlainNumericColumn(ordered.expectancy_r,4,false), ...
    formatPlainNumericColumn(ordered.max_drawdown_pct,4,false), ...
    formatPlainNumericColumn( ...
        ordered.return_drawdown_ratio,4,false), ...
    formatPlainNumericColumn(ordered.is_expectancy_r,4,false), ...
    formatPlainNumericColumn(ordered.oos_expectancy_r,4,false), ...
    formatPlainNumericColumn(ordered.robustness_score,4,false), ...
    ordered.stable_sign, ...
    cached, ...
    formatPlainNumericColumn(ordered.elapsed_seconds,3,false), ...
    'VariableNames',{ ...
    'Rank','Parameter1','Value1','Parameter2','Value2', ...
    'Status','Activity','Equivalent','TargetHits', ...
    'Trades','WinRatePct','NetR','NetPnLUSD', ...
    'ReturnPct','ProfitFactor','ExpectancyR', ...
    'MaxDrawdownPct','ReturnDrawdown','ISExpectancyR', ...
    'OOSExpectancyR','Robustness','StableSign', ...
    'Cached','Seconds'});
end
