function summary = buildTradeDistributionSummaryTable(stats,filterName)
%BUILDTRADEDISTRIBUTIONSUMMARYTABLE Construye la tabla de distribución.

metrics = [ ...
    "Filtro"; ...
    "Trades ejecutados"; ...
    "Resultados positivos"; ...
    "Media"; ...
    "Mediana"; ...
    "Desviación estándar"; ...
    "Percentil 5"; ...
    "Percentil 25"; ...
    "Percentil 75"; ...
    "Percentil 95"; ...
    "Mínimo"; ...
    "Máximo"; ...
    "Asimetría"; ...
    "PnL total"; ...
    "PnL medio"; ...
    "PnL mediano"; ...
    "Aporte del mejor 10 %"; ...
    "MFE medio"; ...
    "MAE medio"; ...
    "Duración media"; ...
    "Contratos medios"; ...
    "Riesgo medio"; ...
    "Rango ORB medio"];

values = [ ...
    string(filterName); ...
    string(stats.trade_count); ...
    formatPercent(stats.positive_pct); ...
    formatR(stats.mean_r); ...
    formatR(stats.median_r); ...
    formatR(stats.std_r); ...
    formatR(stats.p05_r); ...
    formatR(stats.p25_r); ...
    formatR(stats.p75_r); ...
    formatR(stats.p95_r); ...
    formatR(stats.min_r); ...
    formatR(stats.max_r); ...
    formatNumber(stats.skewness_r); ...
    formatUSD(stats.total_pnl_usd); ...
    formatUSD(stats.mean_pnl_usd); ...
    formatUSD(stats.median_pnl_usd); ...
    formatPercent(stats.top_10_contribution_pct); ...
    formatR(stats.mean_mfe_r); ...
    formatR(stats.mean_mae_r); ...
    formatNumber(stats.mean_bars_held); ...
    formatNumber(stats.mean_contracts); ...
    formatUSD(stats.mean_risk_usd); ...
    formatPoints(stats.mean_orb_range_points)];

summary = table(metrics,values, ...
    'VariableNames',{'Metric','Value'});
end

function value = formatR(number)
if isfinite(number)
    value = string(sprintf("%.3f R",number));
else
    value = "N/A";
end
end

function value = formatUSD(number)
if isfinite(number)
    value = string(sprintf("$%.2f",number));
else
    value = "N/A";
end
end

function value = formatPercent(number)
if isfinite(number)
    value = string(sprintf("%.2f %%",number));
else
    value = "N/A";
end
end

function value = formatPoints(number)
if isfinite(number)
    value = string(sprintf("%.2f pts",number));
else
    value = "N/A";
end
end

function value = formatNumber(number)
if isfinite(number)
    value = string(sprintf("%.3f",number));
else
    value = "N/A";
end
end
