function lines = buildTradeFeatureLines(tradeRow,context)
%BUILDTRADEFEATURELINES Construye confluencias y contexto del trade.

arguments
    tradeRow table
    context (1,1) struct = struct()
end

if ismember("crt_high",string(tradeRow.Properties.VariableNames))
    lines = buildCRTFeatureLines(tradeRow,context);
    return;
end

direction = string(readField(tradeRow,"direction",""));
exitReason = string(readField(tradeRow,"exit_reason",""));
orbRange = readField(tradeRow,"orb_range_points",NaN);
riskUsed = readField(tradeRow,"effective_risk_usd",NaN);
riskBudget = readField(tradeRow,"risk_budget_usd",NaN);
mfeR = readField(tradeRow,"mfe_R",NaN);
maeR = readField(tradeRow,"mae_R",NaN);

lines = [ ...
    "Setup"; ...
    "✓ ORB " + direction; ...
    formatCheck("Rango ORB",orbRange," puntos",2); ...
    "✓ Salida: " + exitReason; ...
    formatRisk(riskUsed,riskBudget); ...
    formatCheck("MFE",mfeR," R",3); ...
    formatCheck("MAE",maeR," R",3); ...
    ""; ...
    "Contexto de sesión"; ...
    contextLine(context,"gap_pct","Gap"," %",2); ...
    contextLine(context,"atr14_points","ATR 14"," puntos",2); ...
    percentileLine(context,"atr_percentile_60","Percentil ATR"); ...
    percentileLine(context, ...
        "orb_range_percentile_60","Percentil ORB"); ...
    stringLine(context,"day_of_week","Día"); ...
    stringLine(context,"month","Mes"); ...
    contextLine(context, ...
        "session_return_pct","Retorno sesión"," %",2); ...
    stringLine(context,"session_direction","Dirección sesión"); ...
    trendDayLine(context); ...
    ""; ...
    "Datos todavía no integrados"; ...
    "○ VIX"; ...
    "○ Régimen externo de volatilidad"];

lines = reshape(lines,[],1);
end

function lines = buildCRTFeatureLines(tradeRow,context)
sessionName = string(readField(tradeRow,"session_name",""));
direction = string(readField(tradeRow,"direction",""));
setupStatus = string(readField(tradeRow,"setup_status",""));
orderStatus = string(readField(tradeRow,"order_status",""));
skipReason = string(readField(tradeRow,"skip_reason",""));
exitReason = string(readField(tradeRow,"exit_reason",""));

lines = [ ...
    "CRT 3H — " + sessionName; ...
    "• Setup: " + setupStatus; ...
    "• Orden: " + orderStatus; ...
    "• Dirección: " + valueOrNA(direction); ...
    formatCheck("Rango CRT", ...
        readField(tradeRow,"crt_range_points",NaN)," puntos",2); ...
    formatCheck("Manipulación", ...
        readField(tradeRow,"manipulation_points",NaN)," puntos",2); ...
    formatCheck(entryLevelLabel(tradeRow), ...
        readField(tradeRow,"entry_level",NaN),"",2); ...
    formatCheck("Riesgo teórico", ...
        readField(tradeRow,"risk_points",NaN)," puntos",2); ...
    formatRisk( ...
        readField(tradeRow,"effective_risk_usd",NaN), ...
        readField(tradeRow,"risk_budget_usd",NaN)); ...
    "• Salida: " + valueOrNA(exitReason); ...
    "• No ejecución: " + valueOrNA(skipReason); ...
    ""; ...
    "Contexto de sesión"; ...
    contextLine(context,"atr14_points","ATR 14"," puntos",2); ...
    percentileLine(context,"atr_percentile_60","Percentil ATR"); ...
    stringLine(context,"day_of_week","Día"); ...
    stringLine(context,"month","Mes")];

lines = reshape(lines,[],1);
end

function label = entryLevelLabel(tradeRow)
fraction = readField(tradeRow,"entry_fraction",NaN);
if isfinite(fraction)
    label = "Nivel entrada " + string(sprintf("%.1f %%",100*fraction));
else
    label = "Nivel de entrada";
end
end

function value = valueOrNA(value)
value = string(value);
if strlength(value)==0
    value = "N/A";
end
end

function value = readField(row,name,defaultValue)
if ismember(name,string(row.Properties.VariableNames))
    value = row.(name)(1);
else
    value = defaultValue;
end
end

function line = formatCheck(label,value,suffix,decimals)
if isnumeric(value) && isfinite(value)
    line = "✓ " + label + ": " + ...
        string(sprintf("%.*f",decimals,value)) + suffix;
else
    line = "○ " + label + ": N/A";
end
end

function line = formatRisk(used,budget)
if isfinite(used) && isfinite(budget) && budget>0
    utilization = 100*used/budget;
    line = "✓ Riesgo usado: " + string(sprintf( ...
        "%.2f / %.2f USD (%.1f %%)", ...
        used,budget,utilization));
else
    line = "○ Riesgo usado: N/A";
end
end

function line = contextLine(context,field,label,suffix,decimals)
if isfield(context,field)
    value = context.(field);
else
    value = NaN;
end

if isnumeric(value) && isfinite(value)
    line = "✓ " + label + ": " + ...
        string(sprintf("%.*f",decimals,value)) + suffix;
else
    line = "○ " + label + ": N/A";
end
end

function line = percentileLine(context,field,label)
if isfield(context,field) && isfinite(context.(field))
    line = "✓ " + label + ": P" + ...
        string(sprintf("%.0f",context.(field)));
else
    line = "○ " + label + ": N/A";
end
end

function line = stringLine(context,field,label)
if isfield(context,field) && strlength(string(context.(field)))>0
    line = "✓ " + label + ": " + string(context.(field));
else
    line = "○ " + label + ": N/A";
end
end

function line = trendDayLine(context)
if ~isfield(context,"trend_day")
    line = "○ Día de tendencia: N/A";
elseif context.trend_day
    line = "✓ Día de tendencia";
else
    line = "○ Día de tendencia: No";
end
end
