function reportData = buildResearchReportTable(m)
%BUILDRESEARCHREPORTTABLE Construye la tabla Overview/Report.

leftNames = [ ...
    "PSR";"Total Orders";"Average Loss";"Drawdown"; ...
    "Start Equity";"Net Profit";"Loss Rate"; ...
    "Profit-Loss Ratio";"Beta";"Annual Variance"; ...
    "Tracking Error";"Total Fees";"Drawdown Recovery"];

leftValues = [ ...
    formatPercentOrNA(m.psrPct); ...
    string(m.totalOrders); ...
    sprintf("%.2f %%",m.averageLossPct); ...
    sprintf("%.2f %%",m.maxDrawdownPct); ...
    formatCurrency(m.startEquity); ...
    sprintf("%.2f %%",m.returnPct); ...
    sprintf("%.2f %%",m.lossRatePct); ...
    formatNumberOrNA(m.profitLossRatio); ...
    "N/A"; ...
    formatNumberOrNA(m.annualVariance); ...
    "N/A"; ...
    formatCurrency(m.totalFees); ...
    string(m.drawdownRecoveryTrades)];

rightNames = [ ...
    "Sharpe Ratio";"Average Win";"Compounding Annual Return"; ...
    "Expectancy";"End Equity";"Sortino Ratio";"Win Rate"; ...
    "Alpha";"Annual Standard Deviation";"Information Ratio"; ...
    "Treynor Ratio";"Portfolio Turnover"; ...
    "Estimated Strategy Capacity"];

rightValues = [ ...
    formatNumberOrNA(m.sharpeRatio); ...
    sprintf("%.2f %%",m.averageWinPct); ...
    formatPercentOrNA(m.cagrPct); ...
    formatNumberOrNA(m.expectancyR); ...
    formatCurrency(m.endEquity); ...
    formatNumberOrNA(m.sortinoRatio); ...
    sprintf("%.2f %%",m.winRatePct); ...
    "N/A"; ...
    formatNumberOrNA(m.annualStd); ...
    "N/A"; ...
    "N/A"; ...
    sprintf("%.2f %%",m.turnoverPct); ...
    "N/A"];

reportData = table( ...
    leftNames,leftValues,rightNames,rightValues, ...
    'VariableNames',{'Metric','Value','Metric2','Value2'});
end

function text = formatCurrency(value)
if isnan(value)
    text = "N/A";
else
    text = string(sprintf("$%.2f",value));
end
end

function text = formatPercentOrNA(value)
if isnan(value)
    text = "N/A";
else
    text = string(sprintf("%.3f %%",value));
end
end

function text = formatNumberOrNA(value)
if isnan(value)
    text = "N/A";
else
    text = string(sprintf("%.3f",value));
end
end
