function clearTradeResearchView( ...
    ax,titleLabel,detailsTable,featuresArea)
%CLEARTRADERESEARCHVIEW Reinicia la vista Trade Research.

resetResearchAxes(ax);

text(ax,0.5,0.5, ...
    "Select a trade in the Trades tab", ...
    "HorizontalAlignment","center");

titleLabel.Text = "No trade selected";
detailsTable.Data = table();

featuresArea.Value = reshape([ ...
    "Confluencias disponibles:", ...
    "• ORB direction", ...
    "• ORB range", ...
    "• Exit reason", ...
    "• Risk, MFE and MAE"],[],1);
end
