function showAnalyticsError(ax,summaryTable,sectionName,ME)
%SHOWANALYTICSERROR Muestra un error sin bloquear el dashboard principal.

resetDashboardAxes(ax);

message = string(ME.message);

text( ...
    ax,0.5,0.55, ...
    sectionName + " no pudo actualizarse", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontWeight","bold", ...
    "Color",[0.82 0.08 0.08], ...
    "Interpreter","none");

text( ...
    ax,0.5,0.43, ...
    message, ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","top", ...
    "Color",[0.25 0.25 0.25], ...
    "Interpreter","none");

summaryTable.Data = table( ...
    ["Sección";"Estado";"Error"], ...
    [string(sectionName);"No cargada";message], ...
    'VariableNames',{'Metric','Value'});

drawnow limitrate nocallbacks;
end
