function showTradeResearchError( ...
    ax,titleLabel,detailsTable,featuresArea,tradeIndex,ME)
%SHOWTRADERESEARCHERROR Evita que Research quede bloqueado en Cargando.

resetResearchAxes(ax);

titleLabel.Text = sprintf( ...
    "Error al cargar Trade #%d", ...
    tradeIndex);

message = string(ME.message);

text( ...
    ax,0.5,0.55, ...
    "No se pudo representar este trade", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontWeight","bold", ...
    "Color",[0.82 0.08 0.08]);

text( ...
    ax,0.5,0.45, ...
    message, ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","top", ...
    "Interpreter","none", ...
    "Color",[0.25 0.25 0.25]);

detailsTable.Data = table( ...
    ["Trade";"Estado";"Error"], ...
    ["#"+string(tradeIndex);"No cargado";message], ...
    'VariableNames',{'Metric','Value'});

featuresArea.Value = reshape([ ...
    "Trade Research recuperado del error.", ...
    "Puedes volver a seleccionar la misma fila.", ...
    "", ...
    "Detalle:", ...
    message],[],1);

drawnow limitrate nocallbacks;
end
