function styleTradeDistributionSummaryTable(tableHandle,stats)
%STYLETRADEDISTRIBUTIONSUMMARYTABLE Aplica formato visual al resumen.
%
% - columna de métricas en gris y negrita;
% - resultados favorables en verde;
% - resultados desfavorables en rojo;
% - concentración elevada del beneficio en ámbar.

arguments
    tableHandle
    stats (1,1) struct
end

try
    removeStyle(tableHandle);
catch
end

try
    metricStyle = uistyle( ...
        "BackgroundColor",[0.95 0.95 0.95], ...
        "FontWeight","bold", ...
        "FontColor",[0.18 0.18 0.18]);

    addStyle(tableHandle,metricStyle,"column",1);

    positiveStyle = uistyle( ...
        "BackgroundColor",[0.88 0.96 0.88], ...
        "FontColor",[0.00 0.38 0.05], ...
        "FontWeight","bold");

    negativeStyle = uistyle( ...
        "BackgroundColor",[1.00 0.90 0.90], ...
        "FontColor",[0.65 0.00 0.00], ...
        "FontWeight","bold");

    amberStyle = uistyle( ...
        "BackgroundColor",[1.00 0.95 0.82], ...
        "FontColor",[0.50 0.30 0.00], ...
        "FontWeight","bold");

    signedRows = [ ...
        4,stats.mean_r; ...
        5,stats.median_r; ...
        7,stats.p05_r; ...
        8,stats.p25_r; ...
        9,stats.p75_r; ...
        10,stats.p95_r; ...
        11,stats.min_r; ...
        12,stats.max_r; ...
        14,stats.total_pnl_usd; ...
        15,stats.mean_pnl_usd; ...
        16,stats.median_pnl_usd];

    for i = 1:size(signedRows,1)
        rowIndex = signedRows(i,1);
        value = signedRows(i,2);

        if ~isfinite(value)
            continue;
        elseif value>0
            addStyle( ...
                tableHandle,positiveStyle, ...
                "cell",[rowIndex 2]);
        elseif value<0
            addStyle( ...
                tableHandle,negativeStyle, ...
                "cell",[rowIndex 2]);
        end
    end

    if isfinite(stats.mean_mfe_r)
        addStyle(tableHandle,positiveStyle,"cell",[18 2]);
    end

    if isfinite(stats.mean_mae_r)
        addStyle(tableHandle,negativeStyle,"cell",[19 2]);
    end

    if isfinite(stats.top_10_contribution_pct) && ...
            stats.top_10_contribution_pct>=75
        addStyle(tableHandle,amberStyle,"cell",[17 2]);
    end
catch
    % Compatibilidad defensiva con versiones antiguas de UITable.
end
end
