function updateExposureChart(exposureAxes,executed)
%UPDATEEXPOSURECHART Actualiza exposición acumulada long/short.
%
% LONG siempre se muestra en azul y SHORT siempre en rojo,
% independientemente del perfil o del orden de actualización.

resetDashboardAxes(exposureAxes);

if isempty(executed)
    return;
end

palette = getQuantLabPalette();
tradeNumber = (1:height(executed))';

direction = upper(string(executed.direction));
longRatio = cumsum(direction=="LONG") ./ tradeNumber;
shortRatio = cumsum(direction=="SHORT") ./ tradeNumber;

hold(exposureAxes,"on");

plot( ...
    exposureAxes, ...
    buildTradeTimeline(executed), ...
    longRatio, ...
    "Color",palette.long, ...
    "LineWidth",1.35, ...
    "DisplayName","Long Ratio");

plot( ...
    exposureAxes, ...
    buildTradeTimeline(executed), ...
    shortRatio, ...
    "Color",palette.short, ...
    "LineWidth",1.35, ...
    "DisplayName","Short Ratio");

hold(exposureAxes,"off");

legend( ...
    exposureAxes, ...
    "show", ...
    "Location","best");

ylim(exposureAxes,[0 1]);
grid(exposureAxes,"on");
formatAxesNatural(exposureAxes,"ratio");
end
