function updateDrawdownChart(drawdownAxes,executed,cfg)
%UPDATEDRAWDOWNCHART Actualiza el drawdown porcentual.
%
% El límite superior del eje Y siempre es 0 %.
% La curva y el sombreado utilizan azul primario.

resetDashboardAxes(drawdownAxes);

if isempty(executed)
    return;
end

equity = [ ...
    cfg.risk.initialEquityUSD; ...
    executed.equity_after_usd];

tradeTimeline = buildTradeTimeline(executed);
dates = [tradeTimeline(1)-milliseconds(1);tradeTimeline];

runningPeak = cummax(equity);
drawdownPct = 100 .* (equity-runningPeak) ./ runningPeak;

blueLine = [0.00 0.4470 0.7410];
blueFill = [0.60 0.78 0.93];

hold(drawdownAxes,"on");

area( ...
    drawdownAxes, ...
    dates, ...
    drawdownPct, ...
    "BaseValue",0, ...
    "FaceColor",blueFill, ...
    "FaceAlpha",0.35, ...
    "EdgeColor","none", ...
    "HandleVisibility","off");

plot( ...
    drawdownAxes, ...
    dates, ...
    drawdownPct, ...
    "LineWidth",1.3, ...
    "Color",blueLine, ...
    "HandleVisibility","off");

yline( ...
    drawdownAxes, ...
    0, ...
    "Color",[0.25 0.25 0.25], ...
    "LineWidth",0.7, ...
    "HandleVisibility","off");

hold(drawdownAxes,"off");

grid(drawdownAxes,"on");
ylabel(drawdownAxes,"Drawdown (%)");
formatAxesNatural(drawdownAxes,"percent");

minimumDrawdown = min(drawdownPct,[],"omitnan");

if isempty(minimumDrawdown) || ~isfinite(minimumDrawdown) || ...
        minimumDrawdown==0
    lowerLimit = -1;
else
    lowerLimit = minimumDrawdown - ...
        max(0.25,0.08*abs(minimumDrawdown));
end

ylim(drawdownAxes,[lowerLimit 0]);

if numel(dates)>=2
    xlim(drawdownAxes,[dates(1) dates(end)]);
end
end
