function updateLogsPanel(logsArea,strategyName,profile,metrics)
%UPDATELOGSPANEL Actualiza el resumen textual del backtest.

lines = reshape([ ...
    "QuantLab Dashboard", ...
    "Strategy: " + string(strategyName), ...
    "Profile: " + string(profile), ...
    "Orders: " + string(metrics.totalOrders), ...
    "End equity: " + formatCurrency(metrics.endEquity), ...
    "Return: " + string(sprintf("%.2f %%",metrics.returnPct))], ...
    [],1);

logsArea.Value = lines;
end

function text = formatCurrency(value)
if isnan(value)
    text = "N/A";
else
    text = string(sprintf("$%.2f",value));
end
end
