function updateAnalyticsDashboard( ...
    calendarAxes,calendarSummaryTable, ...
    winRateAxes,expectancyAxes,profitFactorAxes, ...
    sharpeAxes,drawdownAxes,executionAxes, ...
    trades,windowSize)
%UPDATEANALYTICSDASHBOARD Actualiza Calendar y Rolling Analytics.

updateCalendarAnalytics( ...
    calendarAxes, ...
    calendarSummaryTable, ...
    trades);

updateRollingAnalytics( ...
    winRateAxes, ...
    expectancyAxes, ...
    profitFactorAxes, ...
    sharpeAxes, ...
    drawdownAxes, ...
    executionAxes, ...
    trades, ...
    windowSize);
end
