function updateOrdersTable(ordersTable,trades)
%UPDATEORDERSTABLE Actualiza la tabla de órdenes.

preferredColumns = [ ...
    "session_date","session_name","reference_range","signal_name", ...
    "setup_status","order_status", ...
    "direction","entry_start","sweep_time","extreme_time", ...
    "entry_fraction","entry_level","reward_risk_planned", ...
    "order_time","order_price","stop_price","target_price", ...
    "risk_points","risk_budget_usd","risk_per_contract_usd", ...
    "skip_reason","valid","quantity","contracts"];

columns = preferredColumns(ismember( ...
    preferredColumns, ...
    string(trades.Properties.VariableNames)));

ordersTable.Data = formatTableForDisplay(trades(:,columns));
end
