function updateTradesTable(tradesTable,trades)
%UPDATETRADESTABLE Actualiza la tabla de operaciones.

preferredColumns = [ ...
    "session_date","session_name","reference_range","signal_name", ...
    "rules_version","direction", ...
    "entry_fraction","reward_risk_planned","entry_time", ...
    "exit_time","entry_price","exit_price","quantity","contracts", ...
    "gross_R","net_R","gross_pnl_usd","commission_usd", ...
    "net_pnl_usd","equity_after_usd","exit_reason"];

columns = preferredColumns(ismember( ...
    preferredColumns, ...
    string(trades.Properties.VariableNames)));

tradesTable.Data = formatTableForDisplay(trades(:,columns));
end
