function exportScenarioComparison(results,cfg,strategyName)
%EXPORTSCENARIOCOMPARISON Exportador común de escenarios.

arguments
    results (1,1) struct
    cfg (1,1) struct
    strategyName (1,1) string = "STRATEGY"
end

reportDir = getQuantLabReportDirectory(cfg,strategyName);
if ~isfolder(reportDir), mkdir(reportDir); end

if isfield(results,"summaryTable")
    writetable(results.summaryTable, ...
        fullfile(reportDir,strategyName + "_scenario_summary.csv"));
end

fields = string(fieldnames(results));
for field = fields'
    scenario = results.(field);
    if ~isstruct(scenario) || ~isfield(scenario,"trades") || ...
            ~istable(scenario.trades) || isempty(scenario.trades)
        continue;
    end
    writetable(scenario.trades, ...
        fullfile(reportDir, ...
        strategyName + "_trades_" + upper(field) + ".csv"));

    if isfield(scenario,"sessionScenarios") && ...
            isstruct(scenario.sessionScenarios)
        sessionFields = string(fieldnames(scenario.sessionScenarios));
        for sessionField = sessionFields'
            sessionScenario = ...
                scenario.sessionScenarios.(sessionField);
            if ~isstruct(sessionScenario) || ...
                    ~isfield(sessionScenario,"trades") || ...
                    ~istable(sessionScenario.trades) || ...
                    isempty(sessionScenario.trades)
                continue;
            end
            writetable(sessionScenario.trades, ...
                fullfile(reportDir, ...
                strategyName + "_trades_" + upper(field) + ...
                "_" + upper(sessionField) + ".csv"));

            if isfield(sessionScenario,"exitManagementScenarios") && ...
                    isstruct(sessionScenario.exitManagementScenarios)
                exitFields = string(fieldnames( ...
                    sessionScenario.exitManagementScenarios));
                for exitField = exitFields'
                    exitScenario = ...
                        sessionScenario.exitManagementScenarios.(exitField);
                    if ~isstruct(exitScenario) || ...
                            ~isfield(exitScenario,"trades") || ...
                            ~istable(exitScenario.trades) || ...
                            isempty(exitScenario.trades)
                        continue;
                    end
                    writetable(exitScenario.trades, ...
                        fullfile(reportDir, ...
                        strategyName + "_trades_" + upper(field) + ...
                        "_" + upper(sessionField) + ...
                        "_" + upper(exitField) + ".csv"));
                end
            end
        end
    end
end
end
