function state = createInitialMarketState(symbol, marketTimezone)
arguments
    symbol (1,1) string = ""
    marketTimezone (1,1) string = "America/New_York"
end
state = struct();
state.schema_version = "0.6.0";
state.symbol = symbol;
state.market_timezone = marketTimezone;
state.clock = struct("current_time",NaT("TimeZone",marketTimezone), ...
    "session_date",NaT("TimeZone",marketTimezone),"bar_index",0);
state.price = struct("open",NaN,"high",NaN,"low",NaN, ...
    "close",NaN,"volume",NaN,"last_price",NaN);
state.session = struct("is_active",false,"bars_seen",0, ...
    "session_open",NaN,"session_high",NaN,"session_low",NaN, ...
    "session_close",NaN,"orb_completed",false, ...
    "orb_open",NaN,"orb_high",NaN,"orb_low",NaN,"orb_close",NaN);
state.structure = struct("trend","UNDEFINED", ...
    "last_swing_high_price",NaN, ...
    "last_swing_high_time",NaT("TimeZone",marketTimezone), ...
    "last_swing_low_price",NaN, ...
    "last_swing_low_time",NaT("TimeZone",marketTimezone), ...
    "last_structure_label","", ...
    "swing_high_count",0,"swing_low_count",0, ...
    "last_bos","","last_choch","");
state.liquidity = struct("last_sweep_type","", ...
    "last_sweep_price",NaN, ...
    "last_sweep_time",NaT("TimeZone",marketTimezone));
state.fvg = struct("bullish_open_count",0,"bearish_open_count",0, ...
    "last_created_type","", ...
    "last_created_time",NaT("TimeZone",marketTimezone));
state.execution = struct("trade_active",false,"direction","", ...
    "entry_price",NaN,"stop_price",NaN,"target_price",NaN, ...
    "contracts",0,"risk_usd",0);
end
