function output = runMarketStateEngine(data, events, cfg)
timeline = buildEventTimeline(events);
symbol = "";
if ~isempty(data)
    symbol = string(data.symbol(1));
end
state = createInitialMarketState(symbol,cfg.marketTimezone);
snapshotRows = cell(height(data),1);
eventCursor = 1;

for i = 1:height(data)
    bar = data(i,:);
    newSession = i == 1 || ...
        bar.session_date_new_york(1) ~= data.session_date_new_york(i-1);
    if newSession
        state = resetMarketStateForSession( ...
            state,bar.session_date_new_york(1),bar);
    end

    state = updateMarketStateFromBar(state,bar,i);

    while eventCursor <= height(timeline) && ...
            timeline.event_time(eventCursor) <= bar.datetime_new_york(1)
        state = applyEventToMarketState(state,timeline(eventCursor,:));
        eventCursor = eventCursor + 1;
    end

    snapshotRows{i} = table( ...
        state.clock.current_time,state.clock.session_date, ...
        state.clock.bar_index,state.price.close, ...
        state.session.session_high,state.session.session_low, ...
        state.session.orb_completed, ...
        state.structure.last_swing_high_price, ...
        state.structure.last_swing_low_price, ...
        state.structure.swing_high_count, ...
        state.structure.swing_low_count, ...
        string(state.structure.trend), ...
        'VariableNames',{'datetime','session_date','bar_index','close', ...
        'session_high','session_low','orb_completed', ...
        'last_swing_high','last_swing_low', ...
        'swing_high_count','swing_low_count','trend'});
end

output = struct("finalState",state, ...
    "snapshots",vertcat(snapshotRows{:}), ...
    "timeline",timeline, ...
    "timelineSummary",summarizeEventTimeline(timeline));
end
