function strategyTable = listStrategies()
%LISTSTRATEGIES Lista plugins descubiertos automáticamente.

registry = getStrategyRegistry();

if isempty(registry)
    strategyTable = table();
    disp(strategyTable);
    return;
end

strategyTable = table( ...
    string({registry.name})', ...
    string({registry.displayName})', ...
    string({registry.version})', ...
    string({registry.assetClasses})', ...
    logical([registry.enabled])', ...
    string({registry.validationError})', ...
    'VariableNames',{ ...
    'name','display_name','version','asset_classes', ...
    'enabled','validation_error'});

disp(strategyTable);
end
