function output = runStrategy(strategyName,data,cfg)
%RUNSTRATEGY Punto de entrada universal Strategy Plugin v1.

arguments
    strategyName (1,1) string
    data table
    cfg (1,1) struct
end

cfg.instrumentSpec = normalizeInstrumentSpec(cfg);
cfg.sessionSpec = normalizeSessionSpec(cfg);
data = ensureCanonicalBarData(data,cfg);

plugin = resolveStrategyPlugin(strategyName);
validateStrategyData(data,plugin);

if ~ismember(cfg.instrumentSpec.assetClass, ...
        upper(string(plugin.assetClasses)))
    error("QuantLab:StrategyInstrumentMismatch", ...
        "%s no admite %s.",plugin.name,cfg.instrumentSpec.assetClass);
end

if isfield(plugin,"validateConfig")
    plugin.validateConfig(cfg);
end

fprintf('\n=== RUN STRATEGY: %s v%s ===\n', ...
    plugin.name,plugin.version);

[events,context] = plugin.buildEvents(data,cfg);
validateEventTable(events);

missingEvents = setdiff( ...
    string(plugin.requiredEventTypes), ...
    unique(string(events.event_type)));

if ~isempty(missingEvents)
    error("QuantLab:MissingRequiredEvents", ...
        "No se generaron eventos requeridos por %s: %s", ...
        plugin.name,strjoin(missingEvents,", "));
end

if ~isfield(context,"daily") || ~istable(context.daily)
    error("QuantLab:StrategyDailyContext", ...
        "%s debe devolver context.daily como tabla.",plugin.name);
end

results = plugin.run(data,context,events,cfg);
validateStrategyResults(results,cfg,plugin);

metadata = struct( ...
    "core_version","0.25.37", ...
    "strategy_name",plugin.name, ...
    "strategy_display_name",plugin.displayName, ...
    "strategy_version",plugin.version, ...
    "data_contract_version",plugin.dataContractVersion, ...
    "trade_contract_version",plugin.tradeContractVersion, ...
    "instrument",cfg.instrumentSpec.symbol, ...
    "asset_class",cfg.instrumentSpec.assetClass, ...
    "run_timestamp",datetime("now"), ...
    "event_count",height(events), ...
    "session_count",numel(unique(data.session_date)), ...
    "dataset_fingerprint",buildDatasetFingerprint(data,cfg));

output = struct( ...
    "strategy",plugin.name, ...
    "plugin",plugin, ...
    "events",events, ...
    "daily",context.daily, ...
    "results",results, ...
    "metadata",metadata);
end
