function catalog = buildORBFeatureCatalog()
%BUILDORBFEATURECATALOG Metadatos aportados por el plugin ORB.
%
% El Segment Explorer sigue siendo genérico. Este archivo solo mejora
% etiquetas, roles y unidades para la estrategia ORB.

rows = { ...
    "direction","Direction","categorical","","input", ...
        "Categories",true,"ORB","Direction known at entry"; ...
    "orb_range_points","ORB Range","numeric","points","input", ...
        "Quintiles",true,"ORB","Opening range size"; ...
    "risk_points","Initial Risk Distance","numeric","points","input", ...
        "Quintiles",true,"ORB","Entry to stop distance"; ...
    "risk_budget_usd","Risk Budget","numeric","USD","input", ...
        "Quintiles",true,"ORB","Budget before sizing"; ...
    "risk_per_contract_usd","Risk per Contract","numeric","USD","input", ...
        "Quintiles",true,"ORB","Instrument risk per contract"; ...
    "effective_risk_usd","Effective Risk","numeric","USD","input", ...
        "Quintiles",true,"ORB","Actual risk after sizing"; ...
    "contracts","Contracts","numeric","contracts","input", ...
        "Categories",true,"ORB","Position size"; ...
    "day_of_week","Day of Week","categorical","","context", ...
        "Categories",true,"derived","Derived from session date"; ...
    "month_name","Month","categorical","","context", ...
        "Categories",true,"derived","Derived from session date"; ...
    "quarter","Quarter","categorical","","context", ...
        "Categories",true,"derived","Derived from session date"; ...
    "entry_hour","Entry Hour","numeric","hour","context", ...
        "Categories",true,"derived","Derived from entry timestamp"};

catalog = cell2table(rows, ...
    'VariableNames',{ ...
    'name','label','type','unit','role', ...
    'default_grouping','enabled','source','description'});

catalog = normalizeFeatureCatalog(catalog);
end
