function schema = buildORBParameterSchema()
%BUILDORBPARAMETERSCHEMA Parámetros optimizables declarados por ORB.
%
% Los filtros de rango pertenecen al plugin ORB. El motor genérico solo
% aplica rutas dentro de cfg y vuelve a ejecutar la estrategia.

schema = table( ...
    ["orb.rewardRisk"; ...
     "orb.filters.minimumRangePoints"; ...
     "orb.filters.maximumRangePoints"; ...
     "risk.fixedRiskUSD"; ...
     "risk.percentRisk"; ...
     "risk.maximumContracts"], ...
    ["Reward/Risk Target"; ...
     "Minimum ORB Range"; ...
     "Maximum ORB Range"; ...
     "Fixed Risk"; ...
     "Percent Risk"; ...
     "Maximum Contracts"], ...
    ["numeric";"numeric";"numeric";"numeric";"numeric";"integer"], ...
    [10;0;Inf;100;0.01;40], ...
    [1;0;10;25;0.001;1], ...
    [20;150;300;500;0.05;100], ...
    [1;5;10;25;0.001;1], ...
    [1;0;40;25;0.001;1], ...
    [20;80;160;500;0.05;100], ...
    ["R";"points";"points";"USD";"%";"contracts"], ...
    true(6,1), ...
    [true;true;true;false;true;true], ...
    false(6,1), ...
    [ ...
     "Profit target expressed in initial risk multiples"; ...
     "Trade only sessions with ORB range greater than or equal to this value"; ...
     "Trade only sessions with ORB range lower than or equal to this value"; ...
     "Disabled while risk.mode is PERCENT_EQUITY"; ...
     "Active when risk.mode is PERCENT_EQUITY"; ...
     "Maximum position size"], ...
    'VariableNames',{ ...
    'name','label','type','default_value', ...
    'minimum','maximum','step','sweep_start','sweep_stop', ...
    'unit','enabled','optimizable','rebuild_events','description'});

schema = normalizeParameterSchema(schema);
end
